---
title: "[ARDL Cointegration]{.flow}"
author: "[[Zahid Asghar, Professor, School of Economics, QAU](https://zahedasghar.netlify.app)]{style=color:blue;}"
date: "09-01-2024"
date-format: "DD-MM-YYYY"
format: 
  revealjs:
    theme: [default, custom.css,styles.scss]
    toc: true
    code-fold: true
    keep-md: false
    chalkboard: true
    slide-number: c/t
execute: 
  freeze: auto
--- 

## ARDL Cointegration {.scrollable}

::: incremental 

- Pesaran, Shin and Smith (PSS)(2001) test is based on testing cointegration among variables irrespective of the fact whether variables are I(0)/I(1). 

- Test statistics is similar to Wald or F-test but nonstandard 

- Critical values assuming all I(0) for lower bound and I(1) for upper bound

- If test statistics fall outside the range, there is CI without testing variables are I(0)/I(1) 

-   Advantages over conventional methodology 

      1. It can be used with mixture of I(0) and I(1) data. 
      
      2. It involves just a single-equation set-up, making it simple to implement and interpret. 
      
      3. Different variables can be assigned different lag-lengths as they enter the model.
      
:::

## Basic Steps 

{% raw %}
$\begin{aligned}{{Y}_{t}}={{\beta}_{0}}+\sum\limits_{i=1}^{p}{{{\beta}_{1}}{{Y}_{t-i}}+\sum\limits_{i=0}^{{{q}_{1}}}{{{a}_{1}}{{X}_{1,t-i}}\sum\limits_{i=0}^{{{q}_{2}}}{{{a}_{2}}{{X}_{2,t-i}}+}}}\\\sum\limits_{i=0}^{{{q}_{3}}}{{{a}_{3}}{{X}_{3,t-i}}+}\sum\limits_{i=0}^{q4}{{{a}_{4}}{{X}_{4,t-i}}+}{{\varepsilon}_{t}}\end{aligned}$
{% endraw %}

## 

- 1. None of the variables should be I(2)
- 2. Formulate the following equation 

{% raw %}
$\begin{aligned}\Delta {{Y}_{t}}={{\beta}_{0}}+\sum\limits_{i=1}^{p}{{{\beta }_{1}}\Delta{{Y}_{t-i}}+\sum\limits_{i=0}^{{{q}_{1}}}{{{a}_{1}}\Delta{{X}_{1,t-i}}\sum\limits_{i=0}^{{{q}_{2}}}{{{a}_{2}}\Delta{{X}_{2,t-i}}+}}}\\\sum\limits_{i=0}^{{{q}_{3}}}{{{a}_{3}}\Delta{{X}_{3,t-i}}+}\sum\limits_{i=0}^{q4}{{{a}_{4}}\Delta{{X}_{4,t-i}}}\\+{{\theta}_{0}}{{Y}_{t-1}}+{{\theta}_{1}}{{X}_{1,t-1}}+{{\\\theta}_{2}}{{X}_{2,t-1}}+{{\theta}_{3}}{{X}_{3,t-1}}+{{\theta}_{4}}{{X}_{4,t-1}}+{{\varepsilon}_{t}}\end{aligned}$
{% endraw %}

##


-   Test ${{H}_{0}}:{{\theta}_{0}}={{\theta }_{1}}=...={{\theta }_{4}}=0$  
 against the alternative $H_0$ is  not correct. 
 
-   If $H_0$ is rejected, then CI and run 
 ${{Y}_{t}}={{\beta}_{0}}+{{a}_{1}}{{X}_{1,t}}+{{a}_{2}}{{X}_{2,t}}+\\{{a}_{3}}{{X}_{3,t}}+{{a}_{4}}{{X}_{4,t}}+{{\varepsilon}_{t}}$  and as usual ECM 

{% raw %}
$$\Delta {{Y}_{t}}={{\beta}_{0}}+\sum\limits_{i=1}^{p}{{{\beta }_{1}}\Delta{{Y}_{t-i}}+\sum\limits_{i=0}^{{{q}_{1}}}{{{a}_{1}}\Delta{{X}_{1,t-i}}\sum\limits_{i=0}^{{{q}_{2}}}{{{a}_{2}}\Delta{{X}_{2,t-i}}+}}}\\\sum\limits_{i=0}^{{{q}_{3}}}{{{a}_{3}}\Delta{{X}_{3,t-i}}+}\sum\limits_{i=0}^{q4}{{{a}_{4}}\Delta{{X}_{4,t-i}}}+\delta {{Z}_{t-1}}+{{\varepsilon}_{t}}$$
{% endraw %}

where 
{% raw %}
$${{Z}_{t-1}}=\left({{Y}_{t-1}}-{{a}_{0}}-{{a}_{1}}{{X}_{1,t-1}}-{{a}_{2}}{{X}_{2,t-1}}-\\{{a}_{3}}{{X}_{3,t-1}}-{{a}_{4}}{{X}_{4,t-1}}\right)$$ 
{% endraw %}

[How to do perform it in STATA/R](http://rizaudinsahlan.blogspot.com/2016/06/ardl-cointegration-test-with-stata.html)

