{
  "hash": "5a3826c950c0c19142720d4a30ee86e4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"ARDL model\"\nauthor: \"\"\ndate: 'today'\nformat: \n  html:\n    toc: true\n    toc-depth: 2\n    number-sections: true\n    keep-md: false\n\nexecute: \n  echo: false\n  warning: false\n  freeze: auto\nbibliography: ../assets/references.bib\n---\n\n## Summary Statistics\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"jdnddigdzl\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>@import url(\"https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap\");\n#jdnddigdzl table {\n  font-family: Roboto, system-ui, 'Segoe UI', Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#jdnddigdzl thead, #jdnddigdzl tbody, #jdnddigdzl tfoot, #jdnddigdzl tr, #jdnddigdzl td, #jdnddigdzl th {\n  border-style: none;\n}\n\n#jdnddigdzl p {\n  margin: 0;\n  padding: 0;\n}\n\n#jdnddigdzl .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 12px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 3px;\n  border-top-color: rgba(255, 255, 255, 0);\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 1px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#jdnddigdzl .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#jdnddigdzl .gt_title {\n  color: #333333;\n  font-size: 30px;\n  font-weight: bold;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#jdnddigdzl .gt_subtitle {\n  color: #333333;\n  font-size: 16px;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#jdnddigdzl .gt_heading {\n  background-color: #FFFFFF;\n  text-align: left;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jdnddigdzl .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jdnddigdzl .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 3px;\n  border-top-color: rgba(255, 255, 255, 0);\n  border-bottom-style: solid;\n  border-bottom-width: 3px;\n  border-bottom-color: rgba(255, 255, 255, 0);\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jdnddigdzl .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 80%;\n  font-weight: bolder;\n  text-transform: uppercase;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 6px;\n  padding-bottom: 7px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#jdnddigdzl .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 80%;\n  font-weight: bolder;\n  text-transform: uppercase;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#jdnddigdzl .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#jdnddigdzl .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#jdnddigdzl .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 3px;\n  border-bottom-color: rgba(255, 255, 255, 0);\n  vertical-align: bottom;\n  padding-top: 6px;\n  padding-bottom: 6px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#jdnddigdzl .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#jdnddigdzl .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 80%;\n  font-weight: bolder;\n  text-transform: uppercase;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#jdnddigdzl .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 80%;\n  font-weight: bolder;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#jdnddigdzl .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#jdnddigdzl .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#jdnddigdzl .gt_row {\n  padding-top: 6px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: rgba(255, 255, 255, 0);\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#jdnddigdzl .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 80%;\n  font-weight: bolder;\n  text-transform: uppercase;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jdnddigdzl .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#jdnddigdzl .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#jdnddigdzl .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#jdnddigdzl .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jdnddigdzl .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#jdnddigdzl .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#jdnddigdzl .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jdnddigdzl .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jdnddigdzl .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#jdnddigdzl .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jdnddigdzl .gt_striped {\n  background-color: #F5F5F5;\n}\n\n#jdnddigdzl .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jdnddigdzl .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jdnddigdzl .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jdnddigdzl .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jdnddigdzl .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jdnddigdzl .gt_left {\n  text-align: left;\n}\n\n#jdnddigdzl .gt_center {\n  text-align: center;\n}\n\n#jdnddigdzl .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#jdnddigdzl .gt_font_normal {\n  font-weight: normal;\n}\n\n#jdnddigdzl .gt_font_bold {\n  font-weight: bold;\n}\n\n#jdnddigdzl .gt_font_italic {\n  font-style: italic;\n}\n\n#jdnddigdzl .gt_super {\n  font-size: 65%;\n}\n\n#jdnddigdzl .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#jdnddigdzl .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#jdnddigdzl .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#jdnddigdzl .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#jdnddigdzl .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#jdnddigdzl .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#jdnddigdzl .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#jdnddigdzl .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#jdnddigdzl div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"6\" class=\"gt_heading gt_title gt_font_normal gt_bottom_border\" style>Descriptive statistics</td>\n    </tr>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" style=\"background-color: #585D63; color: #FFFFFF; font-size: 10px; font-weight: bold; border-bottom-width: 2.5px; border-bottom-style: solid; border-bottom-color: #585d63;\" scope=\"col\" id=\"Variable\">Variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"background-color: #585D63; color: #FFFFFF; font-size: 10px; font-weight: bold; border-bottom-width: 2.5px; border-bottom-style: solid; border-bottom-color: #585d63;\" scope=\"col\" id=\"Observations\">Observations</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"background-color: #585D63; color: #FFFFFF; font-size: 10px; font-weight: bold; border-bottom-width: 2.5px; border-bottom-style: solid; border-bottom-color: #585d63;\" scope=\"col\" id=\"Mean\">Mean</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"background-color: #585D63; color: #FFFFFF; font-size: 10px; font-weight: bold; border-bottom-width: 2.5px; border-bottom-style: solid; border-bottom-color: #585d63;\" scope=\"col\" id=\"Variance\">Variance</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"background-color: #585D63; color: #FFFFFF; font-size: 10px; font-weight: bold; border-bottom-width: 2.5px; border-bottom-style: solid; border-bottom-color: #585d63;\" scope=\"col\" id=\"Min\">Min</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"background-color: #585D63; color: #FFFFFF; font-size: 10px; font-weight: bold; border-bottom-width: 2.5px; border-bottom-style: solid; border-bottom-color: #585d63;\" scope=\"col\" id=\"Max\">Max</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">tri</td>\n<td headers=\"Observations\" class=\"gt_row gt_right\">129</td>\n<td headers=\"Mean\" class=\"gt_row gt_right\">8.404767e+03</td>\n<td headers=\"Variance\" class=\"gt_row gt_right\">5.173292e+06</td>\n<td headers=\"Min\" class=\"gt_row gt_right\">4.805700e+03</td>\n<td headers=\"Max\" class=\"gt_row gt_right\">1.365807e+04</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left gt_striped\">amihud_illiqudity</td>\n<td headers=\"Observations\" class=\"gt_row gt_right gt_striped\">129</td>\n<td headers=\"Mean\" class=\"gt_row gt_right gt_striped\">1.143788e-04</td>\n<td headers=\"Variance\" class=\"gt_row gt_right gt_striped\">7.228797e-09</td>\n<td headers=\"Min\" class=\"gt_row gt_right gt_striped\">6.815073e-08</td>\n<td headers=\"Max\" class=\"gt_row gt_right gt_striped\">4.131326e-04</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">turn_over_ratio</td>\n<td headers=\"Observations\" class=\"gt_row gt_right\">129</td>\n<td headers=\"Mean\" class=\"gt_row gt_right\">3.429762e-04</td>\n<td headers=\"Variance\" class=\"gt_row gt_right\">6.681290e-09</td>\n<td headers=\"Min\" class=\"gt_row gt_right\">1.728531e-04</td>\n<td headers=\"Max\" class=\"gt_row gt_right\">6.371190e-04</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left gt_striped\">bid_ask_spread</td>\n<td headers=\"Observations\" class=\"gt_row gt_right gt_striped\">129</td>\n<td headers=\"Mean\" class=\"gt_row gt_right gt_striped\">3.653350e-02</td>\n<td headers=\"Variance\" class=\"gt_row gt_right gt_striped\">8.017560e-04</td>\n<td headers=\"Min\" class=\"gt_row gt_right gt_striped\">1.323962e-02</td>\n<td headers=\"Max\" class=\"gt_row gt_right gt_striped\">2.800664e-01</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">pe</td>\n<td headers=\"Observations\" class=\"gt_row gt_right\">129</td>\n<td headers=\"Mean\" class=\"gt_row gt_right\">1.741102e+01</td>\n<td headers=\"Variance\" class=\"gt_row gt_right\">1.324346e+01</td>\n<td headers=\"Min\" class=\"gt_row gt_right\">9.773000e+00</td>\n<td headers=\"Max\" class=\"gt_row gt_right\">2.424900e+01</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left gt_striped\">beta_monthly_leveraged</td>\n<td headers=\"Observations\" class=\"gt_row gt_right gt_striped\">129</td>\n<td headers=\"Mean\" class=\"gt_row gt_right gt_striped\">9.829977e-01</td>\n<td headers=\"Variance\" class=\"gt_row gt_right gt_striped\">1.078852e-07</td>\n<td headers=\"Min\" class=\"gt_row gt_right gt_striped\">9.816000e-01</td>\n<td headers=\"Max\" class=\"gt_row gt_right gt_striped\">9.837000e-01</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">dy</td>\n<td headers=\"Observations\" class=\"gt_row gt_right\">129</td>\n<td headers=\"Mean\" class=\"gt_row gt_right\">3.241860e+00</td>\n<td headers=\"Variance\" class=\"gt_row gt_right\">2.752090e-01</td>\n<td headers=\"Min\" class=\"gt_row gt_right\">2.420000e+00</td>\n<td headers=\"Max\" class=\"gt_row gt_right\">4.800000e+00</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left gt_striped\">annualised_volatility_open</td>\n<td headers=\"Observations\" class=\"gt_row gt_right gt_striped\">129</td>\n<td headers=\"Mean\" class=\"gt_row gt_right gt_striped\">1.659018e+01</td>\n<td headers=\"Variance\" class=\"gt_row gt_right gt_striped\">2.315657e+01</td>\n<td headers=\"Min\" class=\"gt_row gt_right gt_striped\">1.002220e+01</td>\n<td headers=\"Max\" class=\"gt_row gt_right gt_striped\">2.992440e+01</td></tr>\n    <tr><td headers=\"Variable\" class=\"gt_row gt_left\">market_cap</td>\n<td headers=\"Observations\" class=\"gt_row gt_right\">129</td>\n<td headers=\"Mean\" class=\"gt_row gt_right\">1.298655e+13</td>\n<td headers=\"Variance\" class=\"gt_row gt_right\">1.231063e+25</td>\n<td headers=\"Min\" class=\"gt_row gt_right\">7.569386e+12</td>\n<td headers=\"Max\" class=\"gt_row gt_right\">2.127136e+13</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\nThe summary statistics of the financial series that have been incorporated as a dependent and independent variable are shown in Table 1. The study examined the impact of liquidity, market cap, dividend yield, and beta weekly leverage on `tri` using monthly data from January 2013 to September 2023. The gathered from Yahoo Finance, freely available data source. A few common statistics of the data used in the studies are reported in Table 1. A total of 129 observations were included in that data analysis process. The `tri` average isequal to 8404, with minimum values of 4805 and maximum values of 13658. pe, beta monthly, and dy variables are in ratios. As some variables are in ratios while others in numbers, so comparing means and other measures across variables will not make much idea. \n\n## Correlation\n\n\nTo observe association among vaerious variables , correlation (a measure of linear association) is given as follows:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"idcaqvcydw\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>@import url(\"https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap\");\n#idcaqvcydw table {\n  font-family: Roboto, system-ui, 'Segoe UI', Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#idcaqvcydw thead, #idcaqvcydw tbody, #idcaqvcydw tfoot, #idcaqvcydw tr, #idcaqvcydw td, #idcaqvcydw th {\n  border-style: none;\n}\n\n#idcaqvcydw p {\n  margin: 0;\n  padding: 0;\n}\n\n#idcaqvcydw .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 12px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 3px;\n  border-top-color: rgba(255, 255, 255, 0);\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 1px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#idcaqvcydw .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#idcaqvcydw .gt_title {\n  color: #333333;\n  font-size: 30px;\n  font-weight: bold;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#idcaqvcydw .gt_subtitle {\n  color: #333333;\n  font-size: 16px;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#idcaqvcydw .gt_heading {\n  background-color: #FFFFFF;\n  text-align: left;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#idcaqvcydw .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#idcaqvcydw .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 3px;\n  border-top-color: rgba(255, 255, 255, 0);\n  border-bottom-style: solid;\n  border-bottom-width: 3px;\n  border-bottom-color: rgba(255, 255, 255, 0);\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#idcaqvcydw .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 80%;\n  font-weight: bolder;\n  text-transform: uppercase;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 6px;\n  padding-bottom: 7px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#idcaqvcydw .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 80%;\n  font-weight: bolder;\n  text-transform: uppercase;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#idcaqvcydw .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#idcaqvcydw .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#idcaqvcydw .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 3px;\n  border-bottom-color: rgba(255, 255, 255, 0);\n  vertical-align: bottom;\n  padding-top: 6px;\n  padding-bottom: 6px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#idcaqvcydw .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#idcaqvcydw .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 80%;\n  font-weight: bolder;\n  text-transform: uppercase;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#idcaqvcydw .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 80%;\n  font-weight: bolder;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#idcaqvcydw .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#idcaqvcydw .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#idcaqvcydw .gt_row {\n  padding-top: 6px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: rgba(255, 255, 255, 0);\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#idcaqvcydw .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 80%;\n  font-weight: bolder;\n  text-transform: uppercase;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#idcaqvcydw .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#idcaqvcydw .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#idcaqvcydw .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#idcaqvcydw .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#idcaqvcydw .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#idcaqvcydw .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#idcaqvcydw .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#idcaqvcydw .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#idcaqvcydw .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#idcaqvcydw .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#idcaqvcydw .gt_striped {\n  background-color: #F5F5F5;\n}\n\n#idcaqvcydw .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#idcaqvcydw .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#idcaqvcydw .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#idcaqvcydw .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#idcaqvcydw .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#idcaqvcydw .gt_left {\n  text-align: left;\n}\n\n#idcaqvcydw .gt_center {\n  text-align: center;\n}\n\n#idcaqvcydw .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#idcaqvcydw .gt_font_normal {\n  font-weight: normal;\n}\n\n#idcaqvcydw .gt_font_bold {\n  font-weight: bold;\n}\n\n#idcaqvcydw .gt_font_italic {\n  font-style: italic;\n}\n\n#idcaqvcydw .gt_super {\n  font-size: 65%;\n}\n\n#idcaqvcydw .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#idcaqvcydw .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#idcaqvcydw .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#idcaqvcydw .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#idcaqvcydw .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#idcaqvcydw .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#idcaqvcydw .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#idcaqvcydw .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#idcaqvcydw div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"10\" class=\"gt_heading gt_title gt_font_normal gt_bottom_border\" style>Correlation among selected variables</td>\n    </tr>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" style=\"background-color: #585D63; color: #FFFFFF; font-size: 10px; font-weight: bold; border-bottom-width: 2.5px; border-bottom-style: solid; border-bottom-color: #585d63;\" scope=\"col\" id=\"Var\">Var</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"background-color: #585D63; color: #FFFFFF; font-size: 10px; font-weight: bold; border-bottom-width: 2.5px; border-bottom-style: solid; border-bottom-color: #585d63;\" scope=\"col\" id=\"tri\">tri</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"background-color: #585D63; color: #FFFFFF; font-size: 10px; font-weight: bold; border-bottom-width: 2.5px; border-bottom-style: solid; border-bottom-color: #585d63;\" scope=\"col\" id=\"amihud_illiqudity\">amihud_illiqudity</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"background-color: #585D63; color: #FFFFFF; font-size: 10px; font-weight: bold; border-bottom-width: 2.5px; border-bottom-style: solid; border-bottom-color: #585d63;\" scope=\"col\" id=\"turn_over_ratio\">turn_over_ratio</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"background-color: #585D63; color: #FFFFFF; font-size: 10px; font-weight: bold; border-bottom-width: 2.5px; border-bottom-style: solid; border-bottom-color: #585d63;\" scope=\"col\" id=\"bid_ask_spread\">bid_ask_spread</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"background-color: #585D63; color: #FFFFFF; font-size: 10px; font-weight: bold; border-bottom-width: 2.5px; border-bottom-style: solid; border-bottom-color: #585d63;\" scope=\"col\" id=\"pe\">pe</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"background-color: #585D63; color: #FFFFFF; font-size: 10px; font-weight: bold; border-bottom-width: 2.5px; border-bottom-style: solid; border-bottom-color: #585d63;\" scope=\"col\" id=\"beta_monthly_leveraged\">beta_monthly_leveraged</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"background-color: #585D63; color: #FFFFFF; font-size: 10px; font-weight: bold; border-bottom-width: 2.5px; border-bottom-style: solid; border-bottom-color: #585d63;\" scope=\"col\" id=\"dy\">dy</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"background-color: #585D63; color: #FFFFFF; font-size: 10px; font-weight: bold; border-bottom-width: 2.5px; border-bottom-style: solid; border-bottom-color: #585d63;\" scope=\"col\" id=\"annualised_volatility_open\">annualised_volatility_open</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" style=\"background-color: #585D63; color: #FFFFFF; font-size: 10px; font-weight: bold; border-bottom-width: 2.5px; border-bottom-style: solid; border-bottom-color: #585d63;\" scope=\"col\" id=\"market_cap\">market_cap</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Var\" class=\"gt_row gt_left\">tri</td>\n<td headers=\"tri\" class=\"gt_row gt_right\">1.00</td>\n<td headers=\"amihud_illiqudity\" class=\"gt_row gt_right\">−0.15</td>\n<td headers=\"turn_over_ratio\" class=\"gt_row gt_right\">−0.65</td>\n<td headers=\"bid_ask_spread\" class=\"gt_row gt_right\">0.07</td>\n<td headers=\"pe\" class=\"gt_row gt_right\">−0.56</td>\n<td headers=\"beta_monthly_leveraged\" class=\"gt_row gt_right\">0.15</td>\n<td headers=\"dy\" class=\"gt_row gt_right\">0.60</td>\n<td headers=\"annualised_volatility_open\" class=\"gt_row gt_right\">0.39</td>\n<td headers=\"market_cap\" class=\"gt_row gt_right\">0.99</td></tr>\n    <tr><td headers=\"Var\" class=\"gt_row gt_left gt_striped\">amihud_illiqudity</td>\n<td headers=\"tri\" class=\"gt_row gt_right gt_striped\">−0.15</td>\n<td headers=\"amihud_illiqudity\" class=\"gt_row gt_right gt_striped\">1.00</td>\n<td headers=\"turn_over_ratio\" class=\"gt_row gt_right gt_striped\">−0.02</td>\n<td headers=\"bid_ask_spread\" class=\"gt_row gt_right gt_striped\">0.16</td>\n<td headers=\"pe\" class=\"gt_row gt_right gt_striped\">−0.09</td>\n<td headers=\"beta_monthly_leveraged\" class=\"gt_row gt_right gt_striped\">0.20</td>\n<td headers=\"dy\" class=\"gt_row gt_right gt_striped\">0.02</td>\n<td headers=\"annualised_volatility_open\" class=\"gt_row gt_right gt_striped\">0.00</td>\n<td headers=\"market_cap\" class=\"gt_row gt_right gt_striped\">−0.13</td></tr>\n    <tr><td headers=\"Var\" class=\"gt_row gt_left\">turn_over_ratio</td>\n<td headers=\"tri\" class=\"gt_row gt_right\">−0.65</td>\n<td headers=\"amihud_illiqudity\" class=\"gt_row gt_right\">−0.02</td>\n<td headers=\"turn_over_ratio\" class=\"gt_row gt_right\">1.00</td>\n<td headers=\"bid_ask_spread\" class=\"gt_row gt_right\">0.20</td>\n<td headers=\"pe\" class=\"gt_row gt_right\">0.42</td>\n<td headers=\"beta_monthly_leveraged\" class=\"gt_row gt_right\">−0.18</td>\n<td headers=\"dy\" class=\"gt_row gt_right\">−0.36</td>\n<td headers=\"annualised_volatility_open\" class=\"gt_row gt_right\">−0.28</td>\n<td headers=\"market_cap\" class=\"gt_row gt_right\">−0.66</td></tr>\n    <tr><td headers=\"Var\" class=\"gt_row gt_left gt_striped\">bid_ask_spread</td>\n<td headers=\"tri\" class=\"gt_row gt_right gt_striped\">0.07</td>\n<td headers=\"amihud_illiqudity\" class=\"gt_row gt_right gt_striped\">0.16</td>\n<td headers=\"turn_over_ratio\" class=\"gt_row gt_right gt_striped\">0.20</td>\n<td headers=\"bid_ask_spread\" class=\"gt_row gt_right gt_striped\">1.00</td>\n<td headers=\"pe\" class=\"gt_row gt_right gt_striped\">−0.09</td>\n<td headers=\"beta_monthly_leveraged\" class=\"gt_row gt_right gt_striped\">0.04</td>\n<td headers=\"dy\" class=\"gt_row gt_right gt_striped\">0.23</td>\n<td headers=\"annualised_volatility_open\" class=\"gt_row gt_right gt_striped\">0.02</td>\n<td headers=\"market_cap\" class=\"gt_row gt_right gt_striped\">0.09</td></tr>\n    <tr><td headers=\"Var\" class=\"gt_row gt_left\">pe</td>\n<td headers=\"tri\" class=\"gt_row gt_right\">−0.56</td>\n<td headers=\"amihud_illiqudity\" class=\"gt_row gt_right\">−0.09</td>\n<td headers=\"turn_over_ratio\" class=\"gt_row gt_right\">0.42</td>\n<td headers=\"bid_ask_spread\" class=\"gt_row gt_right\">−0.09</td>\n<td headers=\"pe\" class=\"gt_row gt_right\">1.00</td>\n<td headers=\"beta_monthly_leveraged\" class=\"gt_row gt_right\">−0.26</td>\n<td headers=\"dy\" class=\"gt_row gt_right\">−0.75</td>\n<td headers=\"annualised_volatility_open\" class=\"gt_row gt_right\">0.06</td>\n<td headers=\"market_cap\" class=\"gt_row gt_right\">−0.57</td></tr>\n    <tr><td headers=\"Var\" class=\"gt_row gt_left gt_striped\">beta_monthly_leveraged</td>\n<td headers=\"tri\" class=\"gt_row gt_right gt_striped\">0.15</td>\n<td headers=\"amihud_illiqudity\" class=\"gt_row gt_right gt_striped\">0.20</td>\n<td headers=\"turn_over_ratio\" class=\"gt_row gt_right gt_striped\">−0.18</td>\n<td headers=\"bid_ask_spread\" class=\"gt_row gt_right gt_striped\">0.04</td>\n<td headers=\"pe\" class=\"gt_row gt_right gt_striped\">−0.26</td>\n<td headers=\"beta_monthly_leveraged\" class=\"gt_row gt_right gt_striped\">1.00</td>\n<td headers=\"dy\" class=\"gt_row gt_right gt_striped\">0.17</td>\n<td headers=\"annualised_volatility_open\" class=\"gt_row gt_right gt_striped\">0.12</td>\n<td headers=\"market_cap\" class=\"gt_row gt_right gt_striped\">0.16</td></tr>\n    <tr><td headers=\"Var\" class=\"gt_row gt_left\">dy</td>\n<td headers=\"tri\" class=\"gt_row gt_right\">0.60</td>\n<td headers=\"amihud_illiqudity\" class=\"gt_row gt_right\">0.02</td>\n<td headers=\"turn_over_ratio\" class=\"gt_row gt_right\">−0.36</td>\n<td headers=\"bid_ask_spread\" class=\"gt_row gt_right\">0.23</td>\n<td headers=\"pe\" class=\"gt_row gt_right\">−0.75</td>\n<td headers=\"beta_monthly_leveraged\" class=\"gt_row gt_right\">0.17</td>\n<td headers=\"dy\" class=\"gt_row gt_right\">1.00</td>\n<td headers=\"annualised_volatility_open\" class=\"gt_row gt_right\">0.35</td>\n<td headers=\"market_cap\" class=\"gt_row gt_right\">0.65</td></tr>\n    <tr><td headers=\"Var\" class=\"gt_row gt_left gt_striped\">annualised_volatility_open</td>\n<td headers=\"tri\" class=\"gt_row gt_right gt_striped\">0.39</td>\n<td headers=\"amihud_illiqudity\" class=\"gt_row gt_right gt_striped\">0.00</td>\n<td headers=\"turn_over_ratio\" class=\"gt_row gt_right gt_striped\">−0.28</td>\n<td headers=\"bid_ask_spread\" class=\"gt_row gt_right gt_striped\">0.02</td>\n<td headers=\"pe\" class=\"gt_row gt_right gt_striped\">0.06</td>\n<td headers=\"beta_monthly_leveraged\" class=\"gt_row gt_right gt_striped\">0.12</td>\n<td headers=\"dy\" class=\"gt_row gt_right gt_striped\">0.35</td>\n<td headers=\"annualised_volatility_open\" class=\"gt_row gt_right gt_striped\">1.00</td>\n<td headers=\"market_cap\" class=\"gt_row gt_right gt_striped\">0.46</td></tr>\n    <tr><td headers=\"Var\" class=\"gt_row gt_left\">market_cap</td>\n<td headers=\"tri\" class=\"gt_row gt_right\">0.99</td>\n<td headers=\"amihud_illiqudity\" class=\"gt_row gt_right\">−0.13</td>\n<td headers=\"turn_over_ratio\" class=\"gt_row gt_right\">−0.66</td>\n<td headers=\"bid_ask_spread\" class=\"gt_row gt_right\">0.09</td>\n<td headers=\"pe\" class=\"gt_row gt_right\">−0.57</td>\n<td headers=\"beta_monthly_leveraged\" class=\"gt_row gt_right\">0.16</td>\n<td headers=\"dy\" class=\"gt_row gt_right\">0.65</td>\n<td headers=\"annualised_volatility_open\" class=\"gt_row gt_right\">0.46</td>\n<td headers=\"market_cap\" class=\"gt_row gt_right\">1.00</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nCorrelation of `tri` with `market capitalization` is almost perfect while with `liqudity` , its zero, while its negative with `pe`. But as correlation is not same as the causation, therefore, one should observe caution while interpreting results. THese results indicate\n\n\n\n## Trend analysis\n\nFirst step is analysis is always to plot your data for better insight.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lab-03-ardl-in-r_files/figure-html/unnamed-chunk-4-1.png){width=768}\n:::\n\n::: {.cell-output-display}\n![](lab-03-ardl-in-r_files/figure-html/unnamed-chunk-4-2.png){width=768}\n:::\n\n::: {.cell-output-display}\n![](lab-03-ardl-in-r_files/figure-html/unnamed-chunk-4-3.png){width=768}\n:::\n\n::: {.cell-output-display}\n![](lab-03-ardl-in-r_files/figure-html/unnamed-chunk-4-4.png){width=768}\n:::\n\n::: {.cell-output-display}\n![](lab-03-ardl-in-r_files/figure-html/unnamed-chunk-4-5.png){width=768}\n:::\n\n::: {.cell-output-display}\n![](lab-03-ardl-in-r_files/figure-html/unnamed-chunk-4-6.png){width=768}\n:::\n\n::: {.cell-output-display}\n![](lab-03-ardl-in-r_files/figure-html/unnamed-chunk-4-7.png){width=768}\n:::\n\n::: {.cell-output-display}\n![](lab-03-ardl-in-r_files/figure-html/unnamed-chunk-4-8.png){width=768}\n:::\n\n::: {.cell-output-display}\n![](lab-03-ardl-in-r_files/figure-html/unnamed-chunk-4-9.png){width=768}\n:::\n:::\n\n\nFrom these plots, one observes that some series are showing non-stationary behavior and we will test using adf test in the following part.\n\n## Taking log of `tri`, `market cap` and `turn over ratio` \n\nThese three variables have very large values, therefore, log transformation will be made in order to scale down values and to some extent it will make data normally distributed.\n\n## Unit Root Testing using ADF and PP tests\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"Variable\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"adf_stat\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"p_val_adf\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"pp_stat\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"p_val_pp\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"lntri\",\"2\":\"-2.143\",\"3\":\"0.517\",\"4\":\"-15.955\",\"5\":\"0.195\"},{\"1\":\"amihud_illiqudity\",\"2\":\"-4.415\",\"3\":\"0.010\",\"4\":\"-121.545\",\"5\":\"0.010\"},{\"1\":\"ln_turn_over\",\"2\":\"-2.722\",\"3\":\"0.276\",\"4\":\"-88.409\",\"5\":\"0.010\"},{\"1\":\"annualised_volatility_open\",\"2\":\"-3.229\",\"3\":\"0.086\",\"4\":\"-14.980\",\"5\":\"0.251\"},{\"1\":\"ln_mkt_cap\",\"2\":\"-2.587\",\"3\":\"0.333\",\"4\":\"-30.882\",\"5\":\"0.010\"},{\"1\":\"pe\",\"2\":\"-2.031\",\"3\":\"0.564\",\"4\":\"-10.078\",\"5\":\"0.534\"},{\"1\":\"dy\",\"2\":\"-3.302\",\"3\":\"0.074\",\"4\":\"-25.434\",\"5\":\"0.018\"},{\"1\":\"bid_ask_spread\",\"2\":\"-4.742\",\"3\":\"0.010\",\"4\":\"-110.696\",\"5\":\"0.010\"},{\"1\":\"beta_monthly_leveraged\",\"2\":\"-3.035\",\"3\":\"0.146\",\"4\":\"-157.980\",\"5\":\"0.010\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n**ADF test** indicates that all variables with log transformation are non-stationary besides `pe` which is as per expectation as ratio and rates variables are usually stationary. \n Philips-Perron test indicates `have also more or similar results. So one thing is obvious all variables are of the same order of integration, therefore, we shall use ARDL model accordingly. Before we go with seasonal plots to have an idea of seasonality in couple of series.\n\n## Seasonality \nBut before we proceed further, lets have an overview of seasonality and see whether there are strong seasonal patterns are or not.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lab-03-ardl-in-r_files/figure-html/unnamed-chunk-6-1.png){width=768}\n:::\n\n::: {.cell-output-display}\n![](lab-03-ardl-in-r_files/figure-html/unnamed-chunk-6-2.png){width=768}\n:::\n\n::: {.cell-output-display}\n![](lab-03-ardl-in-r_files/figure-html/unnamed-chunk-6-3.png){width=768}\n:::\n\n::: {.cell-output-display}\n![](lab-03-ardl-in-r_files/figure-html/unnamed-chunk-6-4.png){width=768}\n:::\n\n::: {.cell-output-display}\n![](lab-03-ardl-in-r_files/figure-html/unnamed-chunk-6-5.png){width=768}\n:::\n\n::: {.cell-output-display}\n![](lab-03-ardl-in-r_files/figure-html/unnamed-chunk-6-6.png){width=768}\n:::\n\n::: {.cell-output-display}\n![](lab-03-ardl-in-r_files/figure-html/unnamed-chunk-6-7.png){width=768}\n:::\n\n::: {.cell-output-display}\n![](lab-03-ardl-in-r_files/figure-html/unnamed-chunk-6-8.png){width=768}\n:::\n\n::: {.cell-output-display}\n![](lab-03-ardl-in-r_files/figure-html/unnamed-chunk-6-9.png){width=768}\n:::\n:::\n\n\nSeasonality element in most of the cases is not strong and its impact is not significant.\n\n## ARDL\n\nFirst step in ARDL modeling will be to pick the right order of lags structures of each of the variables to be used in the model. It will also help us in deciding whether we have significant observations available for model estimation or not. Its monthly data and seasonality seems not very significant , therefore we have assumed maximum lag order of each of the variable is 4 and then select appropriate lag order as per `AIC` criteria.\n\n## Best model selection \n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n$best_model\n\nTime series regression with \"ts\" data:\nStart = 4, End = 129\n\nCall:\ndynlm::dynlm(formula = full_formula, data = data, start = start, \n    end = end)\n\nCoefficients:\n                     (Intercept)                       L(lntri, 1)  \n                      -1.224e+00                         7.021e-01  \n                     L(lntri, 2)                       L(lntri, 3)  \n                       3.778e-01                        -1.888e-01  \n                    ln_turn_over                L(ln_turn_over, 1)  \n                      -4.186e-03                        -1.165e-02  \n                      ln_mkt_cap                  L(ln_mkt_cap, 1)  \n                       5.361e-01                        -3.663e-01  \n                L(ln_mkt_cap, 2)                  L(ln_mkt_cap, 3)  \n                      -1.664e-01                         9.719e-02  \n                              pe                          L(pe, 1)  \n                       5.963e-03                        -4.679e-03  \n                        L(pe, 2)                          L(pe, 3)  \n                       2.559e-03                        -2.735e-03  \n                              dy                          L(dy, 1)  \n                      -4.145e-02                         2.433e-02  \n                        L(dy, 2)                          L(dy, 3)  \n                       5.200e-02                        -3.278e-02  \n          beta_monthly_leveraged                 amihud_illiqudity  \n                      -9.889e-01                         1.174e+01  \n         L(amihud_illiqudity, 1)                    bid_ask_spread  \n                      -6.296e+01                        -3.838e-02  \n      annualised_volatility_open  L(annualised_volatility_open, 1)  \n                      -1.086e-03                        -2.350e-03  \nL(annualised_volatility_open, 2)  L(annualised_volatility_open, 3)  \n                       3.859e-04                         2.500e-03  \n\n\n$best_order\n                     lntri               ln_turn_over \n                         3                          1 \n                ln_mkt_cap                         pe \n                         3                          3 \n                        dy     beta_monthly_leveraged \n                         3                          0 \n         amihud_illiqudity             bid_ask_spread \n                         1                          0 \nannualised_volatility_open \n                         3 \n\n$top_orders\n   lntri ln_turn_over ln_mkt_cap pe dy beta_monthly_leveraged amihud_illiqudity\n1      3            1          3  3  3                      0                 1\n2      2            0          2  1  2                      0                 1\n3      3            1          3  2  3                      0                 1\n4      3            1          2  3  3                      0                 1\n5      2            0          2  1  2                      0                 1\n6      3            1          3  3  3                      0                 2\n7      2            0          2  0  2                      0                 1\n8      3            2          3  3  3                      0                 1\n9      2            0          2  1  2                      0                 2\n10     2            0          2  1  2                      0                 1\n11     2            0          2  1  1                      0                 1\n12     1            0          1  1  1                      0                 1\n13     3            1          3  3  3                      0                 1\n14     3            2          3  3  3                      0                 1\n15     2            0          2  1  2                      0                 2\n16     2            0          2  1  2                      1                 1\n17     2            1          2  1  2                      1                 1\n18     1            0          1  1  1                      0                 1\n19     2            0          1  1  2                      0                 1\n20     3            2          3  3  3                      0                 1\n   bid_ask_spread annualised_volatility_open       AIC\n1               0                          3 -675.3075\n2               0                          2 -675.1255\n3               0                          3 -674.9866\n4               0                          3 -674.3655\n5               0                          1 -674.2260\n6               0                          3 -673.8163\n7               0                          2 -673.6686\n8               0                          3 -673.3288\n9               0                          2 -673.2300\n10              1                          2 -673.1420\n11              0                          2 -672.1452\n12              0                          0 -671.8965\n13              0                          2 -671.6800\n14              1                          3 -671.3352\n15              1                          2 -671.2455\n16              1                          2 -671.1583\n17              1                          2 -671.0260\n18              0                          1 -671.0108\n19              0                          2 -670.0040\n20              0                          2 -669.9781\n```\n\n\n:::\n:::\n\n\n$lntri=ln_turn_over+ln_mkt_cap+pe+dy+beta_monthly_leveraged+amihud_illiqudity+bid_ask_spread+annualised_volatility_open$\n\n## Select the best model using lag length `AIC` criteria\n\n`ardl(3,1,3,3,3,0,1,0,3)` is found to be the best model using lag length selectio criteria based on AIC. And we shall use this best model to proceed further.\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"term\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"estimate\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"std.error\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"statistic\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"p.value\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"(Intercept)\",\"2\":\"-1.224\",\"3\":\"4.971\",\"4\":\"-0.246\",\"5\":\"0.806\"},{\"1\":\"L(lntri, 1)\",\"2\":\"0.702\",\"3\":\"0.097\",\"4\":\"7.252\",\"5\":\"0.000\"},{\"1\":\"L(lntri, 2)\",\"2\":\"0.378\",\"3\":\"0.110\",\"4\":\"3.429\",\"5\":\"0.001\"},{\"1\":\"L(lntri, 3)\",\"2\":\"-0.189\",\"3\":\"0.092\",\"4\":\"-2.047\",\"5\":\"0.043\"},{\"1\":\"ln_turn_over\",\"2\":\"-0.004\",\"3\":\"0.010\",\"4\":\"-0.425\",\"5\":\"0.672\"},{\"1\":\"L(ln_turn_over, 1)\",\"2\":\"-0.012\",\"3\":\"0.010\",\"4\":\"-1.169\",\"5\":\"0.245\"},{\"1\":\"ln_mkt_cap\",\"2\":\"0.536\",\"3\":\"0.052\",\"4\":\"10.317\",\"5\":\"0.000\"},{\"1\":\"L(ln_mkt_cap, 1)\",\"2\":\"-0.366\",\"3\":\"0.079\",\"4\":\"-4.628\",\"5\":\"0.000\"},{\"1\":\"L(ln_mkt_cap, 2)\",\"2\":\"-0.166\",\"3\":\"0.081\",\"4\":\"-2.060\",\"5\":\"0.042\"},{\"1\":\"L(ln_mkt_cap, 3)\",\"2\":\"0.097\",\"3\":\"0.063\",\"4\":\"1.537\",\"5\":\"0.127\"},{\"1\":\"pe\",\"2\":\"0.006\",\"3\":\"0.002\",\"4\":\"3.061\",\"5\":\"0.003\"},{\"1\":\"L(pe, 1)\",\"2\":\"-0.005\",\"3\":\"0.003\",\"4\":\"-1.633\",\"5\":\"0.106\"},{\"1\":\"L(pe, 2)\",\"2\":\"0.003\",\"3\":\"0.003\",\"4\":\"0.880\",\"5\":\"0.381\"},{\"1\":\"L(pe, 3)\",\"2\":\"-0.003\",\"3\":\"0.002\",\"4\":\"-1.363\",\"5\":\"0.176\"},{\"1\":\"dy\",\"2\":\"-0.041\",\"3\":\"0.010\",\"4\":\"-4.171\",\"5\":\"0.000\"},{\"1\":\"L(dy, 1)\",\"2\":\"0.024\",\"3\":\"0.013\",\"4\":\"1.811\",\"5\":\"0.073\"},{\"1\":\"L(dy, 2)\",\"2\":\"0.052\",\"3\":\"0.014\",\"4\":\"3.769\",\"5\":\"0.000\"},{\"1\":\"L(dy, 3)\",\"2\":\"-0.033\",\"3\":\"0.011\",\"4\":\"-3.006\",\"5\":\"0.003\"},{\"1\":\"beta_monthly_leveraged\",\"2\":\"-0.989\",\"3\":\"4.887\",\"4\":\"-0.202\",\"5\":\"0.840\"},{\"1\":\"amihud_illiqudity\",\"2\":\"11.736\",\"3\":\"18.715\",\"4\":\"0.627\",\"5\":\"0.532\"},{\"1\":\"L(amihud_illiqudity, 1)\",\"2\":\"-62.962\",\"3\":\"20.315\",\"4\":\"-3.099\",\"5\":\"0.003\"},{\"1\":\"bid_ask_spread\",\"2\":\"-0.038\",\"3\":\"0.059\",\"4\":\"-0.653\",\"5\":\"0.515\"},{\"1\":\"annualised_volatility_open\",\"2\":\"-0.001\",\"3\":\"0.001\",\"4\":\"-0.844\",\"5\":\"0.401\"},{\"1\":\"L(annualised_volatility_open, 1)\",\"2\":\"-0.002\",\"3\":\"0.002\",\"4\":\"-1.398\",\"5\":\"0.165\"},{\"1\":\"L(annualised_volatility_open, 2)\",\"2\":\"0.000\",\"3\":\"0.002\",\"4\":\"0.226\",\"5\":\"0.822\"},{\"1\":\"L(annualised_volatility_open, 3)\",\"2\":\"0.002\",\"3\":\"0.001\",\"4\":\"2.137\",\"5\":\"0.035\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nCoefficients of each variable and required lags is given in the table. `ardl(3,1,3,3,3,0,1,0,3)` is the best model. So this model has 17 coefficients to estimate from a sample of 129 observations which seems fine.\n\n## ARDL model estimation\n\nProblem with applying OLS is that some variables are non-stationary and some are stationary, which will lead to spurious regression. Therefore, we shall first we estimate the UECM (Unrestricted Error Correction Model) of the underlying `ardl(3,1,3,3,3,0,1,0,3)`\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nTime series regression with \"ts\" data:\nStart = 4, End = 129\n\nCall:\ndynlm::dynlm(formula = full_formula, data = data, start = start, \n    end = end)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.038674 -0.007579 -0.000001  0.007464  0.056027 \n\nCoefficients:\n                                      Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                         -1.224e+00  4.971e+00  -0.246  0.80602    \nL(lntri, 1)                         -1.089e-01  4.544e-02  -2.397  0.01840 *  \nL(ln_turn_over, 1)                  -1.584e-02  1.285e-02  -1.233  0.22060    \nL(ln_mkt_cap, 1)                     1.006e-01  5.167e-02   1.947  0.05432 .  \nL(pe, 1)                             1.109e-03  1.060e-03   1.046  0.29806    \nL(dy, 1)                             2.096e-03  9.059e-03   0.231  0.81752    \nbeta_monthly_leveraged              -9.889e-01  4.887e+00  -0.202  0.84005    \nL(amihud_illiqudity, 1)             -5.123e+01  2.717e+01  -1.885  0.06230 .  \nbid_ask_spread                      -3.838e-02  5.876e-02  -0.653  0.51512    \nL(annualised_volatility_open, 1)    -5.501e-04  5.702e-04  -0.965  0.33696    \nd(L(lntri, 1))                      -1.890e-01  9.835e-02  -1.921  0.05754 .  \nd(L(lntri, 2))                       1.888e-01  9.224e-02   2.047  0.04325 *  \nd(ln_turn_over)                     -4.186e-03  9.845e-03  -0.425  0.67162    \nd(ln_mkt_cap)                        5.361e-01  5.197e-02  10.317  < 2e-16 ***\nd(L(ln_mkt_cap, 1))                  6.917e-02  7.648e-02   0.904  0.36793    \nd(L(ln_mkt_cap, 2))                 -9.719e-02  6.324e-02  -1.537  0.12745    \nd(pe)                                5.963e-03  1.948e-03   3.061  0.00284 ** \nd(L(pe, 1))                          1.760e-04  2.066e-03   0.085  0.93226    \nd(L(pe, 2))                          2.735e-03  2.006e-03   1.363  0.17580    \nd(dy)                               -4.145e-02  9.939e-03  -4.171 6.47e-05 ***\nd(L(dy, 1))                         -1.922e-02  1.114e-02  -1.725  0.08761 .  \nd(L(dy, 2))                          3.278e-02  1.091e-02   3.006  0.00335 ** \nd(amihud_illiqudity)                 1.174e+01  1.872e+01   0.627  0.53202    \nd(annualised_volatility_open)       -1.086e-03  1.286e-03  -0.844  0.40068    \nd(L(annualised_volatility_open, 1)) -2.886e-03  1.199e-03  -2.407  0.01792 *  \nd(L(annualised_volatility_open, 2)) -2.500e-03  1.170e-03  -2.137  0.03502 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.01503 on 100 degrees of freedom\nMultiple R-squared:  0.889,\tAdjusted R-squared:  0.8612 \nF-statistic: 32.03 on 25 and 100 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\nF-statisitic indicate that variables in the model are collectively important for forecasting stock market turn over.\n\n## RECM (Restricted Error Correction Model)\n\nUnderlying `ardl(3,1,3,3,3,0,1,0,3)`, allowing the constant to join the long-run relationship (case\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nTime series regression with \"zooreg\" data:\nStart = 4, End = 129\n\nCall:\ndynlm::dynlm(formula = full_formula, data = data, start = start, \n    end = end)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.038674 -0.007579 -0.000001  0.007464  0.056027 \n\nCoefficients:\n                                     Estimate Std. Error t value Pr(>|t|)    \nd(L(lntri, 1))                      -0.188957   0.083114  -2.273 0.024958 *  \nd(L(lntri, 2))                       0.188833   0.079091   2.388 0.018683 *  \nd(ln_turn_over)                     -0.004186   0.006892  -0.607 0.544902    \nd(ln_mkt_cap)                        0.536131   0.044985  11.918  < 2e-16 ***\nd(L(ln_mkt_cap, 1))                  0.069169   0.065048   1.063 0.289968    \nd(L(ln_mkt_cap, 2))                 -0.097195   0.057111  -1.702 0.091631 .  \nd(pe)                                0.005963   0.001747   3.414 0.000901 ***\nd(L(pe, 1))                          0.000176   0.001810   0.097 0.922733    \nd(L(pe, 2))                          0.002735   0.001834   1.491 0.138855    \nd(dy)                               -0.041452   0.007946  -5.216 8.76e-07 ***\nd(L(dy, 1))                         -0.019222   0.009218  -2.085 0.039393 *  \nd(L(dy, 2))                          0.032782   0.009332   3.513 0.000646 ***\nd(amihud_illiqudity)                11.736418  13.464191   0.872 0.385301    \nd(annualised_volatility_open)       -0.001086   0.001077  -1.007 0.315956    \nd(L(annualised_volatility_open, 1)) -0.002886   0.001010  -2.858 0.005107 ** \nd(L(annualised_volatility_open, 2)) -0.002500   0.001006  -2.485 0.014474 *  \nect                                 -0.108906   0.021828  -4.989 2.31e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.0144 on 109 degrees of freedom\n  (0 observations deleted due to missingness)\nMultiple R-squared:  0.8932,\tAdjusted R-squared:  0.8766 \nF-statistic: 53.64 on 17 and 109 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n### Test for cointegration\n\nLet's test if there is a long-run levels relationship (cointegration) using the bounds test from Pesaran et al. (2001). The bounds F-test (under the case 2) rejects the NULL hypothesis (let's say, assuming alpha = 0.01) with p-value = 0.004418.\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBounds F-test (Wald) for no cointegration\n\ndata:  d(lntri) ~ -1 + d(L(lntri, 1)) + d(L(lntri, 2)) + d(ln_turn_over) +     d(ln_mkt_cap) + d(L(ln_mkt_cap, 1)) + d(L(ln_mkt_cap, 2)) +     d(pe) + d(L(pe, 1)) + d(L(pe, 2)) + d(dy) + d(L(dy, 1)) +     d(L(dy, 2)) + d(amihud_illiqudity) + d(annualised_volatility_open) +     d(L(annualised_volatility_open, 1)) + d(L(annualised_volatility_open,     2)) + ect\nF = 5.1686, p-value = 0.000567\nalternative hypothesis: Possible cointegration\nnull values:\n   k    T \n   8 1000 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBounds t-test for no cointegration\n\ndata:  d(lntri) ~ L(lntri, 1) + L(ln_turn_over, 1) + L(ln_mkt_cap, 1) +     L(pe, 1) + L(dy, 1) + beta_monthly_leveraged + L(amihud_illiqudity,     1) + bid_ask_spread + L(annualised_volatility_open, 1) +     d(L(lntri, 1)) + d(L(lntri, 2)) + d(ln_turn_over) + d(ln_mkt_cap) +     d(L(ln_mkt_cap, 1)) + d(L(ln_mkt_cap, 2)) + d(pe) + d(L(pe,     1)) + d(L(pe, 2)) + d(dy) + d(L(dy, 1)) + d(L(dy, 2)) + d(amihud_illiqudity) +     d(annualised_volatility_open) + d(L(annualised_volatility_open,     1)) + d(L(annualised_volatility_open, 2))\nt = -2.3966, Lower-bound I(0) = -3.4327, Upper-bound I(1) = -5.3469,\np-value = 0.7892\nalternative hypothesis: Possible cointegration\nnull values:\n   k    T \n   8 1000 \n```\n\n\n:::\n:::\n\n\nSo t=-2.3966 lies below lower limit and indicates there is no cointegration and p-value is also 0.7892 indicating no cointegration. Therefore, there is no long run relationship between stock market turn over and different variables included in the model. However, in the short run variables affect turn over.\n\n## Short-run \n\nHere we have the short-run coefficients (with standard errors, t-statistics and p-values) as there is no cointegration from Bounds test for cointegration.\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"Term\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"Estimate\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Std. Error\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"t value\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Pr(>|t|)\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"(Intercept)\",\"2\":\"-1.224\",\"3\":\"4.971\",\"4\":\"-0.246\",\"5\":\"0.806\",\"_rn_\":\"1\"},{\"1\":\"ln_turn_over\",\"2\":\"-0.004\",\"3\":\"0.010\",\"4\":\"-0.425\",\"5\":\"0.672\",\"_rn_\":\"2\"},{\"1\":\"ln_mkt_cap\",\"2\":\"0.536\",\"3\":\"0.052\",\"4\":\"10.317\",\"5\":\"0.000\",\"_rn_\":\"3\"},{\"1\":\"pe\",\"2\":\"0.006\",\"3\":\"0.002\",\"4\":\"3.061\",\"5\":\"0.003\",\"_rn_\":\"4\"},{\"1\":\"dy\",\"2\":\"-0.041\",\"3\":\"0.010\",\"4\":\"-4.171\",\"5\":\"0.000\",\"_rn_\":\"5\"},{\"1\":\"beta_monthly_leveraged\",\"2\":\"-0.989\",\"3\":\"4.887\",\"4\":\"-0.202\",\"5\":\"0.840\",\"_rn_\":\"6\"},{\"1\":\"amihud_illiqudity\",\"2\":\"11.736\",\"3\":\"18.715\",\"4\":\"0.627\",\"5\":\"0.532\",\"_rn_\":\"7\"},{\"1\":\"bid_ask_spread\",\"2\":\"-0.038\",\"3\":\"0.059\",\"4\":\"-0.653\",\"5\":\"0.515\",\"_rn_\":\"8\"},{\"1\":\"annualised_volatility_open\",\"2\":\"-0.001\",\"3\":\"0.001\",\"4\":\"-0.844\",\"5\":\"0.401\",\"_rn_\":\"9\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\n\nWe can also estimate and visualize the delay multipliers along with their standard errors.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](lab-03-ardl-in-r_files/figure-html/unnamed-chunk-13-1.png){width=768}\n:::\n:::\n\nThese graphs also indicate that some variables have short run impact before it settles down in 4 to 5 months. This analysis indicate that overall there is short run relationship among `tri` and other variables and play effective role.\n\nThese graphs indicate that most of the variables have almost same impact throughtout time while certain variables affect stock for 4 to 5 months before their impact becomes absorbed. ",
    "supporting": [
      "lab-03-ardl-in-r_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}