#rm(list=ls())
library(readxl)
#setwd("C:/Users/Dr.Zahid/OneDrive - Higher Education Commission")
Pot_Onion<-read_xlsx("Potato-Onion1.xlsx",col_names =  TRUE)
Pot_Onion<-data.frame(Pot_Onion)
library(tidyverse)
#install.packages("lubridate")
library(lubridate)
library(dplyr)
library(ggplot2)
library(ggfortify)
theme_set(theme_minimal())
ggplot(Pot_Onion,aes(Date, POTATOES,color=City)) +
  geom_line()
Isb<-filter(Pot_Onion,City=='Islamabad')
glimpse(Isb)
ggplot(Isb,aes(Date, ONION)) +
  geom_line()
# Seasonal decomposition
par(mfrow=c(1,2))
acf(Isb$ONION)
pacf(Isb$ONION)
decompose(Isb$POTATOES)
dts<-diff(Isb$ONION,12)
head(dts)
plot(dts)
acf(dts)
pacf(dts)
ddts<-diff(dts,1)
plot(ddts)
acf(ddts)
pacf(ddts)
str(Isb)
library(forecast)
library(seasonal)
library(seasonalview)
myts <- ts(Isb$POTATOES, start=c(2008, 7), end=c(2015, 7), frequency=12) 
decompose(myts)
glimpse(myts)
#as.numeric(Potato$POTATOES)
autoplot(myts)
ggseasonplot(myts)
ggseasonplot(myts,polar = TRUE)

ggsubseriesplot(myts)


#plot(myts)
# subset the time series (Aug 2014 to July 2015)
myts2 <- window(myts, start=c(2014, 8), end=c(2015, 7)) 
#seasonplot(myts)
fit <- arima(myts, order=c(1, 0, 0))
summary(fit)
# plot series
#plot(myts)
# Seasonal decomposition
fit <- stl(myts, s.window="period")
autoplot(fit)
par(mfrow=c(1,2))
ggAcf(myts)
ggPacf(myts)
ggAcf(dts)
ggPacf(dts)

ddts<-diff(dts,1)
autoplot(ddts)
ggAcf(ddts)
ggPacf(ddts)




library(forecast)
seasonplot(myts)
fit <- arima(myts, order=c(1, 0, 0))
summary(fit)
forecast.Arima(x=myts, h=5)
head(myts)
tail(myts)
auto.arima(myts)

auto.arima(x=myts,seasonal = FALSE)
library(seasonal)
decompose(myts)
##install.packages("seasonalview")
library(seasonalview)
library("shiny")
view(seas(myts))
adf(myts)

