{
  "hash": "77c55dd598cda80777894cf464b39a53",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"When Technology Outruns the Forecast: Experience Curves and Pakistan's Solar Price Collapse\"\nsubtitle: \"Wright's Law vs Moore's Law, the identification trap, and scenario-based price forecasting for policy\"\nauthor: \"Prof. Dr. Zahid Asghar\"\ndate: today\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    number-sections: true\n    code-fold: show\n    code-tools: true\n    theme: cosmo\n    fig-width: 8\n    fig-height: 5\n    embed-resources: true\n    include-in-header:\n      text: |\n        <style>\n        h1, h2, h3 { color: #2C5F2D; }\n        h1 { border-bottom: 2px solid #8B7355; padding-bottom: 6px; }\n        a { color: #8B7355; }\n        .callout-important .callout-title { background-color: #2C5F2D22; }\n        body { font-family: Georgia, 'Gill Sans MT', Calibri, sans-serif; }\n        </style>\nparams:\n  data_path: \"data/experiencecurveDataset_maria.csv\"\nexecute:\n  warning: false\n  message: false\n---\n\n## Why technological forecasting is different\n\nMacroeconomic forecasting treats price as a stochastic process: the trend is\n\"drift,\" a nuisance parameter estimated and extrapolated. Technological\nforecasting treats price as a *function of accumulated deployment*. Wright's\nLaw (Wright, 1936) states that unit cost falls a fixed percentage with every\ndoubling of cumulative production; Moore's Law-type formulations posit a fixed\nexponential decline in calendar time. The distinction is not academic. It is\nthe reason the IEA under-forecast solar deployment and over-forecast solar\ncosts in essentially every World Energy Outlook for two decades, and it is the\nreason the ARIMA models of the companion analysis lost, out of sample, to a\nnaive random walk: a statistical model has no concept of a technology whose\ncost declines *because* it is being deployed.\n\nThis note estimates the experience-curve relationship for Pakistan's solar\npanel prices (January 2017 - May 2026, n = 113), subjects it to the\neconometric discipline it is usually spared, and converts it into a\nscenario-based five-year price forecast. Two findings complicate the naive\nstory in instructive ways, and both are treated as central results: the\nWright/Moore identification trap, and the reduced-form (imported) nature of\nthe local learning curve.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npkgs <- c(\"forecast\", \"ggplot2\", \"scales\", \"knitr\")\ninvisible(lapply(pkgs, function(x) if (!requireNamespace(x, quietly = TRUE))\n  install.packages(x, repos = \"https://cran.r-project.org\")))\nlibrary(forecast); library(ggplot2); library(scales); library(knitr)\n\nbrand_green <- \"#2C5F2D\"; brand_brown <- \"#8B7355\"\n```\n:::\n\n\n## Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- read.csv(params$data_path, stringsAsFactors = FALSE)\ndf$Date <- as.Date(df$Date, format = \"%d/%m/%Y\")\ndf <- df[order(df$Date), ]\nstopifnot(!anyNA(df[, 4:6]))\n\np  <- df$log_commodity_price          # Pakistan panel price (log)\nq  <- df$log_cumulative_capacity_mw   # Pakistan cumulative capacity (log MW)\nps <- df$log_polysilicon_usd          # global polysilicon price (log)\nQ  <- exp(q); n <- nrow(df); t <- 1:n\n\nkable(head(df, 6), caption = \"First six observations\")\n```\n\n::: {.cell-output-display}\n\n\nTable: First six observations\n\n|Area     |Date       |Commodity.type | log_commodity_price| log_cumulative_capacity_mw| log_polysilicon_usd|\n|:--------|:----------|:--------------|-------------------:|--------------------------:|-------------------:|\n|Pakistan |2017-01-01 |Panels         |           -0.967584|                   4.182813|              2.8603|\n|Pakistan |2017-02-01 |Panels         |           -0.967584|                   4.729686|              2.8746|\n|Pakistan |2017-03-01 |Panels         |           -0.967584|                   5.519058|              2.8100|\n|Pakistan |2017-04-01 |Panels         |           -0.967584|                   5.920130|              2.6187|\n|Pakistan |2017-05-01 |Panels         |           -0.967584|                   6.279197|              2.6754|\n|Pakistan |2017-06-01 |Panels         |           -0.967584|                   6.359383|              2.7074|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nannual_add <- tapply(Q, format(df$Date, \"%Y\"), max) -\n              tapply(Q, format(df$Date, \"%Y\"), min)\nadd_df <- data.frame(Year = names(annual_add), MW = as.numeric(annual_add))\nggplot(add_df, aes(Year, MW)) +\n  geom_col(fill = brand_green) +\n  scale_y_continuous(labels = comma) +\n  labs(x = NULL, y = \"MW added\") + theme_minimal()\n```\n\n::: {.cell-output-display}\n![Annual capacity additions (MW): the diffusion S-curve in action](solar_experience_curve_analysis_files/figure-html/additions-1.png){width=768}\n:::\n:::\n\n\nCumulative capacity grew from 66 MW to\n55,744 MW - 9.7 doublings in\nnine years. Annual additions exploded from roughly 690 MW in 2017 to about\n15 GW in 2024, timed exactly with the global panel price collapse, before\ndecelerating visibly in 2025-2026 as buy-back reform and tax uncertainty\narrived. Note for later: the deceleration matters for the scenario ceilings\nin @sec-scenarios.\n\n## Wright's Law vs Moore's Law {#sec-wright-moore}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(df, aes(log_cumulative_capacity_mw, log_commodity_price)) +\n  geom_point(color = brand_green, alpha = 0.7) +\n  geom_smooth(method = \"lm\", se = TRUE, color = brand_brown) +\n  labs(x = \"log cumulative capacity (MW)\", y = \"log panel price\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![The experience-curve view: log price against log cumulative capacity](solar_experience_curve_analysis_files/figure-html/wright-plot-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm_wright <- lm(p ~ q)      # price ~ cumulative experience\nm_moore  <- lm(p ~ t)      # price ~ calendar time\nb_w <- -coef(m_wright)[\"q\"]\n\ncomp <- data.frame(\n  Model = c(\"Wright (experience)\", \"Moore (time trend)\"),\n  Slope = c(round(coef(m_wright)[\"q\"], 4), round(coef(m_moore)[\"t\"], 5)),\n  `R2`  = c(round(summary(m_wright)$r.squared, 3),\n            round(summary(m_moore)$r.squared, 3)),\n  Implied = c(paste0(percent(1 - 2^(-b_w), 0.1), \" per doubling\"),\n              paste0(percent(1 - exp(12 * coef(m_moore)[\"t\"]), 0.1), \" per year\"))\n)\nkable(comp, caption = \"Wright vs Moore on the same series\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Wright vs Moore on the same series\n\n|   |Model               |    Slope|    R2|Implied            |\n|:--|:-------------------|--------:|-----:|:------------------|\n|q  |Wright (experience) | -0.24950| 0.735|15.9% per doubling |\n|t  |Moore (time trend)  | -0.01137| 0.748|12.8% per year     |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"cor(log capacity, time) =\", round(cor(q, t), 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ncor(log capacity, time) = 0.9763 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"R2 of q ~ t (exponential-growth check):\",\n    round(summary(lm(q ~ t))$r.squared, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR2 of q ~ t (exponential-growth check): 0.953 \n```\n\n\n:::\n:::\n\n\n::: {.callout-important}\n## The identification trap\nThe naive Wright regression implies a learning rate of\n15.9% per doubling - deceptively close to the\ncanonical ~20% global solar figure. But the Moore time-trend fits this sample\n*slightly better*, and log-capacity correlates with calendar time at\n0.976. This is the Nagy et al. (2013) result live in our own\ndata: when deployment grows exponentially, experience and time are\nobservationally near-equivalent, and no regression on a single national series\ncan establish that deployment *causes* cost decline. Any policy argument built\non \"our deployment drives learning\" is unidentified here.\n:::\n\n## Econometric guards {#sec-guards}\n\nExperience curves are usually estimated as static log-log regressions on two\ntrending series - exactly the setting in which spurious fit flourishes. Three\nguards are applied: first differences, cointegration testing with correct\ncritical values, and a dynamic OLS estimator for the long-run elasticities.\n\n### First differences\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfd  <- lm(diff(p) ~ diff(q))\nfd2 <- lm(diff(p) ~ diff(q) + diff(ps))\nkable(round(summary(fd2)$coefficients, 4),\n      caption = \"First-difference regression: monthly price changes\")\n```\n\n::: {.cell-output-display}\n\n\nTable: First-difference regression: monthly price changes\n\n|            | Estimate| Std. Error| t value| Pr(>&#124;t&#124;)|\n|:-----------|--------:|----------:|-------:|------------------:|\n|(Intercept) |  -0.0107|     0.0067| -1.5980|             0.1129|\n|diff(q)     |   0.0177|     0.0579|  0.3057|             0.7604|\n|diff(ps)    |   0.0484|     0.0442|  1.0966|             0.2753|\n\n\n:::\n:::\n\n\nMonth to month, capacity growth predicts nothing about price changes (the\nWright slope collapses to zero, t ≈ 0.3). This is not a failure of the data -\nit is the economically correct result. Pakistan holds roughly 2-3% of global\ncumulative solar capacity; the learning happens in Chinese factories, and\nPakistan *imports* the learning curve. The local price-capacity relationship\nalso runs substantially in reverse: global price declines trigger Pakistani\nadoption surges (the 2023-24 additions boom). What looks like a learning curve\nis, in the short run, a diffusion curve wearing its clothes.\n\n### Cointegration with correct critical values\n\n\n::: {.cell}\n\n```{.r .cell-code}\neg2 <- lm(p ~ q)          # bivariate\neg3 <- lm(p ~ q + ps)     # trivariate\ntau <- function(res) {\n  r <- res; d <- diff(r); l <- r[-length(r)]\n  summary(lm(d ~ l - 1))$coefficients[1, \"t value\"]\n}\ncat(\"EG tau, p ~ q      :\", round(tau(residuals(eg2)), 3),\n    \" (5% MacKinnon crit ~ -3.37)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEG tau, p ~ q      : -2.522  (5% MacKinnon crit ~ -3.37)\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"EG tau, p ~ q + ps :\", round(tau(residuals(eg3)), 3),\n    \" (5% MacKinnon crit ~ -3.80)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEG tau, p ~ q + ps : -3.586  (5% MacKinnon crit ~ -3.80)\n```\n\n\n:::\n:::\n\n\nPrice and capacity alone are not cointegrated. Adding polysilicon moves the\nstatistic to the borderline of its (correct, MacKinnon) critical value: the\nlong-run anchor, to the extent one exists, is *joint* - global technological\nprogress proxied by cumulative deployment, plus the upstream input cost.\n\n### DOLS long-run elasticities and the error-correction structure\n\n\n::: {.cell}\n\n```{.r .cell-code}\nk <- 2\nlead_lag <- function(x, j) {\n  if (j > 0) c(x[-(1:j)], rep(NA, j)) else if (j < 0)\n    c(rep(NA, -j), x[1:(length(x) + j)]) else x\n}\ndq <- c(NA, diff(q)); dps <- c(NA, diff(ps))\nD  <- data.frame(p = p, q = q, ps = ps)\nfor (j in -k:k) {\n  D[[paste0(\"dq\",  j)]] <- lead_lag(dq,  j)\n  D[[paste0(\"dps\", j)]] <- lead_lag(dps, j)\n}\ndols <- lm(p ~ ., data = D)\ncd <- summary(dols)$coefficients\nb_q <- cd[\"q\", \"Estimate\"]; b_ps <- cd[\"ps\", \"Estimate\"]\nkable(round(cd[c(\"q\", \"ps\"), ], 4),\n      caption = \"DOLS (Stock-Watson) long-run elasticities, leads/lags k = 2\")\n```\n\n::: {.cell-output-display}\n\n\nTable: DOLS (Stock-Watson) long-run elasticities, leads/lags k = 2\n\n|   | Estimate| Std. Error|  t value| Pr(>&#124;t&#124;)|\n|:--|--------:|----------:|--------:|------------------:|\n|q  |  -0.2203|     0.0105| -20.9153|                  0|\n|ps |   0.2924|     0.0168|  17.3946|                  0|\n\n\n:::\n\n```{.r .cell-code}\ncat(\"DOLS-implied learning rate:\", percent(1 - 2^(b_q), 0.1), \"per doubling\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDOLS-implied learning rate: 14.2% per doubling\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr3  <- residuals(eg3)\necm <- lm(diff(p) ~ r3[-n] + diff(q) + diff(ps))\nkable(round(summary(ecm)$coefficients, 4),\n      caption = \"Error-correction model for monthly price changes\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Error-correction model for monthly price changes\n\n|            | Estimate| Std. Error| t value| Pr(>&#124;t&#124;)|\n|:-----------|--------:|----------:|-------:|------------------:|\n|(Intercept) |  -0.0082|     0.0067| -1.2293|             0.2216|\n|r3[-n]      |  -0.0983|     0.0489| -2.0098|             0.0469|\n|diff(q)     |  -0.0222|     0.0604| -0.3666|             0.7146|\n|diff(ps)    |   0.0634|     0.0442|  1.4342|             0.1544|\n\n\n:::\n\n```{.r .cell-code}\nlambda <- coef(ecm)[\"r3[-n]\"]\ncat(\"Adjustment speed:\", round(lambda, 3), \"per month | half-life:\",\n    round(log(0.5) / log(1 + lambda), 1), \"months\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAdjustment speed: -0.098 per month | half-life: 6.7 months\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Current disequilibrium: price is\",\n    percent(exp(tail(r3, 1)) - 1, 0.1), \"above the long-run relation\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCurrent disequilibrium: price is 22.5% above the long-run relation\n```\n\n\n:::\n:::\n\n\n::: {.callout-important}\n## The disequilibrium premium\nAs of May 2026 the panel price sits roughly\n22.5% **above** the estimated long-run\nrelation - the footprint of the 2026 GST scare and the polysilicon rebound at\nthe end of the sample. The error-correction term (significant, half-life about\n6.7 months) implies steady downward\nreversion pressure if policy uncertainty clears. This is a falsifiable\nnear-term prediction that no ARIMA can generate, because a drift model has no\nconcept of \"above equilibrium.\" It is also a direct measure of what policy\n*signaling alone* costs consumers: the 18% GST never passed, yet its shadow is\nin the price.\n:::\n\n## Decomposing the 2017-2026 decline\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndq_tot <- q[n] - q[1]; dps_tot <- ps[n] - ps[1]; dp_tot <- p[n] - p[1]\nc_q  <- b_q  * dq_tot\nc_ps <- b_ps * dps_tot\ndec <- data.frame(\n  Component = c(\"Capacity / technological progress (proxy)\",\n                \"Polysilicon input cost\",\n                \"Unexplained residual (tax, tariff, FX, margins)\"),\n  `Log contribution` = round(c(c_q, c_ps, dp_tot - c_q - c_ps), 3),\n  `Share of fitted decline` = c(percent(c_q / (c_q + c_ps), 1),\n                                percent(c_ps / (c_q + c_ps), 1), \"-\")\n)\nkable(dec, caption = \"Decomposition of the actual log price change (Jan 2017 - May 2026)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Decomposition of the actual log price change (Jan 2017 - May 2026)\n\n|Component                                       | Log.contribution|Share.of.fitted.decline |\n|:-----------------------------------------------|----------------:|:-----------------------|\n|Capacity / technological progress (proxy)       |           -1.486|76%                     |\n|Polysilicon input cost                          |           -0.470|24%                     |\n|Unexplained residual (tax, tariff, FX, margins) |            0.804|-                       |\n\n\n:::\n:::\n\n\nRoughly 76% of the fitted decline tracks the\ndeployment/learning proxy and 24% tracks\npolysilicon. The sizeable positive residual is domestic: it is the wedge that\nGST episodes, import tariffs, rupee depreciation, and dealer margins drive\nbetween the world module price and what a Pakistani buyer actually pays.\n\n## Uncertainty in the learning rate\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(42)\nB <- 2000; bl <- 12; nb <- ceiling(n / bl)\nsl <- numeric(B)\nfor (i in 1:B) {\n  starts <- sample(1:(n - bl + 1), nb, replace = TRUE)\n  idx <- unlist(lapply(starts, function(s) s:(s + bl - 1)))[1:n]\n  sl[i] <- coef(lm(p[idx] ~ q[idx] + ps[idx]))[2]\n}\nlr_ci <- 1 - 2^(quantile(sl, c(0.95, 0.5, 0.05)))\ncat(\"Learning rate 90% interval:\", percent(lr_ci[1], 0.1), \"to\",\n    percent(lr_ci[3], 0.1), \"| median\", percent(lr_ci[2], 0.1), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLearning rate 90% interval: 9.2% to 17.9% | median 12.6% \n```\n\n\n:::\n:::\n\n\nA twelve-month block bootstrap puts the learning rate between roughly\n9.2% and 17.9% per doubling.\nCarrying this parameter uncertainty into the forecast - rather than reporting\na single curve - is what separates the probabilistic experience-curve\ntradition (Way et al., 2022) from both deterministic \"law\" extrapolation and\nfalsely-narrow ARIMA intervals.\n\n## Scenario engine: capacity paths to price paths {#sec-scenarios}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_logistic <- function(K) {\n  if (any(Q >= K)) return(NULL)\n  z <- log(Q / (K - Q))\n  f <- lm(z ~ t)\n  list(K = K, a = coef(f)[1], b = coef(f)[2],\n       ss = sum((Q - K / (1 + exp(-fitted(f))))^2))\n}\ngrid <- Filter(Negate(is.null), lapply(seq(60000, 400000, 5000), fit_logistic))\nbest <- grid[[which.min(sapply(grid, `[[`, \"ss\"))]]\ncat(\"Best-fit logistic saturation ceiling K =\", comma(best$K), \"MW\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBest-fit logistic saturation ceiling K = 150,000 MW\n```\n\n\n:::\n\n```{.r .cell-code}\nH <- 60; t_f <- (n + 1):(n + H)\ncap_path <- function(K, a, b) K / (1 + exp(-(a + b * t_f)))\nscen <- list(\n  baseline    = { f <- fit_logistic(best$K);  cap_path(f$K, f$a, f$b) },\n  constrained = { f <- fit_logistic(100000);  cap_path(f$K, f$a, f$b) },\n  accelerated = { f <- fit_logistic(250000);  cap_path(f$K, f$a, f$b) }\n)\n\nps_f <- tryCatch(\n  as.numeric(forecast(auto.arima(ts(ps, frequency = 12)), h = H)$mean),\n  error = function(e) rep(ps[n], H))\n\na0 <- coef(eg3)[1]\nforecast_price <- function(cap, b_q_use = b_q) {\n  pf <- numeric(H); pc <- p[n]\n  for (h in 1:H) {\n    p_star <- a0 + b_q_use * log(cap[h]) + b_ps * ps_f[h]\n    pc <- pc + lambda * (pc - p_star)\n    pf[h] <- pc\n  }\n  pf\n}\npaths <- sapply(scen, forecast_price)\n\nfan <- sapply(sample(sl, 500), function(bq) forecast_price(scen$baseline, bq))\nfan_lo <- apply(fan, 1, quantile, 0.05)\nfan_hi <- apply(fan, 1, quantile, 0.95)\n```\n:::\n\n\nThe engine has three moving parts: (i) a logistic diffusion curve fitted to\ncumulative capacity, with the saturation ceiling K chosen by grid search\n(best fit near 150,000 MW) and bracketed by a policy-constrained\nscenario (K = 100 GW: net-billing and tax friction bite) and an accelerated\nscenario (K = 250 GW: batteries unlock a second adoption wave); (ii) an\nauxiliary ARIMA projection of polysilicon; (iii) the error-correction\nforecaster, in which the price converges at rate\n0.098/month toward a *moving* equilibrium defined by the\nDOLS elasticities. The forecast therefore respects both the current\ndisequilibrium premium and the falling technological anchor.\n\n\n::: {.cell}\n\n```{.r .cell-code}\narima_fc <- tryCatch(\n  as.numeric(forecast(auto.arima(ts(p, frequency = 12)), h = H)$mean),\n  error = function(e) rep(NA, H))\nnaive_fc <- rep(p[n], H)\n\ndates_f <- seq(df$Date[n] + 31, by = \"month\", length.out = H)\nplot_df <- rbind(\n  data.frame(Date = df$Date, value = p, series = \"Actual\"),\n  data.frame(Date = dates_f, value = paths[, \"baseline\"],    series = \"Wright-ECM baseline (K=150GW)\"),\n  data.frame(Date = dates_f, value = paths[, \"constrained\"], series = \"Policy-constrained (K=100GW)\"),\n  data.frame(Date = dates_f, value = paths[, \"accelerated\"], series = \"Accelerated (K=250GW)\"),\n  data.frame(Date = dates_f, value = arima_fc,               series = \"ARIMA drift\"),\n  data.frame(Date = dates_f, value = naive_fc,               series = \"Naive\")\n)\nribbon_df <- data.frame(Date = dates_f, lo = fan_lo, hi = fan_hi)\nggplot(plot_df, aes(Date, value, color = series)) +\n  geom_ribbon(data = ribbon_df, aes(x = Date, ymin = lo, ymax = hi),\n              inherit.aes = FALSE, alpha = 0.15, fill = brand_green) +\n  geom_line(linewidth = 0.8) +\n  scale_color_manual(values = c(\n    \"Actual\" = \"black\",\n    \"Wright-ECM baseline (K=150GW)\" = brand_green,\n    \"Policy-constrained (K=100GW)\" = brand_brown,\n    \"Accelerated (K=250GW)\" = \"#4C9A2A\",\n    \"ARIMA drift\" = \"steelblue\", \"Naive\" = \"grey55\")) +\n  labs(y = \"log panel price\", x = NULL, color = NULL,\n       subtitle = \"Ribbon: 90% learning-rate uncertainty on the baseline\") +\n  theme_minimal() + theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![Five-year forecasts: technological (scenario fan) vs statistical benchmarks](solar_experience_curve_analysis_files/figure-html/fan-chart-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfc_tbl <- data.frame(\n  Horizon      = c(\"12 months\", \"36 months\", \"60 months\"),\n  Baseline     = round(paths[c(12, 36, 60), \"baseline\"], 3),\n  Constrained  = round(paths[c(12, 36, 60), \"constrained\"], 3),\n  Accelerated  = round(paths[c(12, 36, 60), \"accelerated\"], 3),\n  ARIMA        = round(arima_fc[c(12, 36, 60)], 3),\n  Naive        = round(naive_fc[c(12, 36, 60)], 3)\n)\nkable(fc_tbl, caption = \"Forecast comparison (log price)\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Forecast comparison (log price)\n\n|Horizon   | Baseline| Constrained| Accelerated|  ARIMA| Naive|\n|:---------|--------:|-----------:|-----------:|------:|-----:|\n|12 months |   -2.623|      -2.602|      -2.643| -2.072| -2.12|\n|36 months |   -2.889|      -2.834|      -2.945| -2.072| -2.12|\n|60 months |   -2.953|      -2.879|      -3.038| -2.072| -2.12|\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Baseline implied cumulative price change at 60 months:\",\n    percent(exp(paths[60, \"baseline\"] - p[n]) - 1, 0.1), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nBaseline implied cumulative price change at 60 months: -56.5% \n```\n\n\n:::\n:::\n\n\nThe baseline implies a further decline of roughly\n56.5% over five years, but\nthe honest headline is the width of the fan: at 60 months the 90% band spans\nabout -3.68 to -1.98 in log terms. The\nscenarios diverge slowly at 12 months and widely at 60 - technological\nforecasts earn their keep precisely at the horizons where statistical models\nextrapolate blind.\n\n## What this means for policy\n\n::: {.callout-important}\n## Policy relevance\n\n- **Planning institutions are structurally exposed.** IGCEP-style generation\n  planning and DISCO revenue models built on ARIMA-class or static cost\n  assumptions will keep being ambushed: Pakistan's ~56 GW of largely\n  behind-the-meter capacity arrived because official projections treated cost\n  declines as drift rather than as a function of deployment. The February 2026\n  net-billing rush is the institutional aftershock of a forecasting failure.\n- **Suppressing adoption does not stop the cost decline - it shifts its\n  composition.** An 18% GST or an Rs 11/unit buy-back pushes households toward\n  self-consumption plus storage; batteries sit on their own ~25-30% learning\n  curve and will hit the grid as a second, larger surprise on a predictable\n  schedule.\n- **Policy signaling has a measurable price.** The\n  22.5% disequilibrium premium at the end of\n  the sample is the cost of GST *uncertainty alone* - the tax never passed,\n  yet its shadow is in the price paid by every buyer in early 2026.\n- **The right planning input is a scenario range, not a point forecast.**\n  Tariff design, cross-subsidy recovery, and IPP capacity-payment exposure\n  should be stress-tested against the fan above, in the spirit of Way et al.\n  (2022): on experience-curve evidence, the fast-transition path is the\n  cheap path, and models that assume static technology costs compound against\n  the state.\n:::\n\n## Key references\n\nNagy, B., Farmer, J. D., Bui, Q. M., & Trancik, J. E. (2013). Statistical\nbasis for predicting technological progress. *PLoS ONE*, 8(2), e52669.\n\nWay, R., Ives, M. C., Mealy, P., & Farmer, J. D. (2022). Empirically grounded\ntechnology forecasts and the energy transition. *Joule*, 6(9), 2057-2082.\n\nWright, T. P. (1936). Factors affecting the cost of airplanes. *Journal of the\nAeronautical Sciences*, 3(4), 122-128.\n\nKavlak, G., McNerney, J., & Trancik, J. E. (2018). Evaluating the causes of\ncost reduction in photovoltaic modules. *Energy Policy*, 123, 700-710.\n\n## Reproducibility\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.6.0 (2026-04-24 ucrt)\nPlatform: x86_64-w64-mingw32/x64\nRunning under: Windows 11 x64 (build 22621)\n\nMatrix products: default\n  LAPACK version 3.12.1\n\nlocale:\n[1] LC_COLLATE=English_Pakistan.utf8  LC_CTYPE=English_Pakistan.utf8   \n[3] LC_MONETARY=English_Pakistan.utf8 LC_NUMERIC=C                     \n[5] LC_TIME=English_Pakistan.utf8    \n\ntime zone: Asia/Karachi\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n[1] knitr_1.51     scales_1.4.0   ggplot2_4.0.3  forecast_9.0.2\n\nloaded via a namespace (and not attached):\n [1] Matrix_1.7-5       gtable_0.3.6       jsonlite_2.0.0     dplyr_1.2.1       \n [5] compiler_4.6.0     tidyselect_1.2.1   Rcpp_1.1.1-1       parallel_4.6.0    \n [9] splines_4.6.0      yaml_2.3.12        fastmap_1.2.0      lattice_0.22-9    \n[13] R6_2.6.1           labeling_0.4.3     generics_0.1.4     htmlwidgets_1.6.4 \n[17] tibble_3.3.1       timeDate_4052.112  pillar_1.11.1      RColorBrewer_1.1-3\n[21] rlang_1.2.0        urca_1.3-4         xfun_0.57          S7_0.2.2          \n[25] otel_0.2.0         cli_3.6.6          mgcv_1.9-4         withr_3.0.2       \n[29] magrittr_2.0.5     digest_0.6.39      grid_4.6.0         rstudioapi_0.18.0 \n[33] lifecycle_1.0.5    nlme_3.1-169       fracdiff_1.5-3     vctrs_0.7.3       \n[37] evaluate_1.0.5     glue_1.8.1         farver_2.1.2       zoo_1.8-15        \n[41] colorspace_2.1-2   rmarkdown_2.31     tools_4.6.0        pkgconfig_2.0.3   \n[45] htmltools_0.5.9   \n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "solar_experience_curve_analysis_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}