{
  "hash": "bdefb33e103c70e2a3df6cc48ec7916e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"ARDL model\"\nauthor: \"Zahid Asghar\"\ndate: 'today'\nformat: \n  html:\n    toc: true\n    toc-depth: 2\n    number-sections: true\n    keep-md: false\n\nexecute: \n  echo: false\n  warning: false\n  freeze: auto\nbibliography: references.bib\n---\n\n\n\n## Data Analysis\n\nPlease find attached the dataset for our analysis. Our primary objective is to understand how liquidity factors impact stock market performance To measure liquidity, we will consider the following variables: turnover ratio, Amihud liquidity, and bid-ask spread which These are key metrics that are known to influence stock market dynamics.\n\nControl Variables: In addition to liquidity metrics, we will consider other control variables, such as price-to-earnings (PE) ratio, beta, dividend yield (DY), and market capitalization. These are important as they can impact stock returns independently of liquidity.\n\n## ARDL Model\n\nWe will employ the AutoRegressive Distributed Lag (ARDL) model to analyze the relationship between these variables. The ARDL model is suitable for investigating long-term relationships between variables and is especially useful when the data may be non-stationary. It accounts for lagged values of the dependent and independent variables, which is crucial for understanding dynamics over time @shah2023\n\n## Steps for data analysis\n\nFirst we convert data in proper time series format and inspect it.\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 129  29\n```\n\n\n:::\n:::\n\n\n\nThere are 129 rows and 29 columns.\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 129\nColumns: 29\n$ date                         <date> 2023-09-30, 2023-08-31, 2023-07-31, 2023…\n$ annualised_volatility_close  <dbl> 16.7525, 17.0132, 17.0193, 17.9165, 18.80…\n$ annualised_volatility_high   <dbl> 14.1396, 14.4823, 14.8715, 15.5432, 16.21…\n$ annualised_volatility_low    <dbl> 15.4383, 15.8605, 15.8441, 16.2231, 16.86…\n$ annualised_volatility_open   <dbl> 17.0132, 17.0193, 17.9165, 18.8078, 19.58…\n$ annualised_volatility_volume <dbl> 8139.071, 11742.070, 11119.030, 11097.453…\n$ beta_four_weekly_leveraged   <dbl> 0.9845, 0.9695, 0.9847, 0.9697, 0.9844, 0…\n$ beta_monthly_leveraged       <dbl> 0.9834, 0.9831, 0.9833, 0.9829, 0.9832, 0…\n$ beta_weekly_leveraged        <dbl> 0.9956, 0.9962, 0.9959, 0.9957, 0.9950, 0…\n$ close                        <dbl> 73238.11, 74953.73, 78977.89, 76027.83, 7…\n$ close_price_previous_day     <dbl> 74824.09, 75256.19, 78506.90, 74892.51, 7…\n$ dy                           <dbl> 4.27, 4.42, 4.41, 4.57, 4.01, 3.82, 3.81,…\n$ ey                           <dbl> 9.563, 9.372, 9.389, 10.231, 9.377, 8.431…\n$ high                         <dbl> 75667.77, 79212.41, 78981.89, 78595.25, 7…\n$ low                          <dbl> 72826.06, 72890.82, 73915.39, 73805.30, 7…\n$ market_cap                   <dbl> 1.733024e+13, 1.959894e+13, 2.041460e+13,…\n$ market_cap_free_float        <dbl> 6.205234e+12, 6.396902e+12, 6.745352e+12,…\n$ open                         <dbl> 74953.73, 78977.89, 76027.83, 75067.47, 7…\n$ pe                           <dbl> 10.456, 10.669, 10.649, 9.773, 10.663, 11…\n$ tri                          <dbl> 12800.43, 13006.44, 13658.07, 13131.28, 1…\n$ tri_percentage_change        <dbl> -2.12, -0.40, 0.60, 1.52, -1.14, 0.12, -0…\n$ value                        <dbl> 3217036557, 4325386481, 3731541229, 54481…\n$ volume                       <dbl> 4252121612, 4976005667, 4195569025, 56051…\n$ bid_ask_spread               <dbl> 0.01913689, 0.04156118, 0.03313663, 0.031…\n$ turn_over_ratio              <dbl> 0.0001856314, 0.0002206949, 0.0001827879,…\n$ absolute_returns             <dbl> 0.022889054, 0.050952995, 0.038802370, 0.…\n$ volume_trillion              <dbl> 318.7124, 392.9944, 318.9800, 420.7657, 4…\n$ amihud_illiqudity            <dbl> 7.181728e-05, 1.296532e-04, 1.216451e-04,…\n$ liqudity                     <dbl> 13924.226, 7712.882, 8220.632, 32889.559,…\n```\n\n\n:::\n:::\n\n\n\nEach columns in its proper context , i-e date and numerical format.\n\n## Plot, plot and plot\n\nFirst step is analysis is always to plot your data for better insight.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](ardl_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](ardl_files/figure-html/unnamed-chunk-4-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](ardl_files/figure-html/unnamed-chunk-4-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](ardl_files/figure-html/unnamed-chunk-4-4.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](ardl_files/figure-html/unnamed-chunk-4-5.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](ardl_files/figure-html/unnamed-chunk-4-6.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](ardl_files/figure-html/unnamed-chunk-4-7.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](ardl_files/figure-html/unnamed-chunk-4-8.png){width=672}\n:::\n:::\n\n\n\nFrom these plots, one observes that some series are showing non-stationary behavior and we will test using adf test in the following part.\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAugmented Dickey-Fuller Test\n\ndata:  tri\nDickey-Fuller = -2.4174, Lag order = 5, p-value = 0.403\nalternative hypothesis: stationary\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAugmented Dickey-Fuller Test\n\ndata:  amihud_illiqudity\nDickey-Fuller = -4.4148, Lag order = 5, p-value = 0.01\nalternative hypothesis: stationary\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAugmented Dickey-Fuller Test\n\ndata:  turn_over_ratio\nDickey-Fuller = -2.6285, Lag order = 5, p-value = 0.3153\nalternative hypothesis: stationary\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAugmented Dickey-Fuller Test\n\ndata:  bid_ask_spread\nDickey-Fuller = -4.7415, Lag order = 5, p-value = 0.01\nalternative hypothesis: stationary\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAugmented Dickey-Fuller Test\n\ndata:  beta_monthly_leveraged\nDickey-Fuller = -3.0355, Lag order = 5, p-value = 0.1461\nalternative hypothesis: stationary\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAugmented Dickey-Fuller Test\n\ndata:  dy\nDickey-Fuller = -3.3024, Lag order = 5, p-value = 0.07398\nalternative hypothesis: stationary\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAugmented Dickey-Fuller Test\n\ndata:  market_cap\nDickey-Fuller = -2.4583, Lag order = 5, p-value = 0.386\nalternative hypothesis: stationary\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAugmented Dickey-Fuller Test\n\ndata:  annualised_volatility_open\nDickey-Fuller = -3.229, Lag order = 5, p-value = 0.08622\nalternative hypothesis: stationary\n```\n\n\n:::\n:::\n\n\n\nWe have a mix of the series. In some series , hypothesis series is non-stationary is rejected and in others its not. Therefore, we shall use ARDL model accordingly. Before we go with seasonal plots to have an idea of seasonality in couple of series.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](ardl_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](ardl_files/figure-html/unnamed-chunk-6-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](ardl_files/figure-html/unnamed-chunk-6-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](ardl_files/figure-html/unnamed-chunk-6-4.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](ardl_files/figure-html/unnamed-chunk-6-5.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](ardl_files/figure-html/unnamed-chunk-6-6.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](ardl_files/figure-html/unnamed-chunk-6-7.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](ardl_files/figure-html/unnamed-chunk-6-8.png){width=672}\n:::\n:::\n\n\n\nSeasonality element in most of the cases is not strong and its impact is not significant.\n\n## ARDL\n\nFirst step in ARDL modeling will be to pick the right order of lags structures of each of the variables to be used in the model. It will also help us in deciding whether we have significant observations available for model estimation or not. Its monthly data and seasonality seems not very significant , therefore we have assumed maximum lag order of each of the variable is 4 and then select appropriate lag order as per `AIC` criteria.\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n$best_model\n\nTime series regression with \"ts\" data:\nStart = 5, End = 129\n\nCall:\ndynlm::dynlm(formula = full_formula, data = data, start = start, \n    end = end)\n\nCoefficients:\n                     (Intercept)                         L(tri, 1)  \n                      -6.243e+03                         6.940e-01  \n                       L(tri, 2)                 amihud_illiqudity  \n                       1.607e-01                         3.800e+04  \n         L(amihud_illiqudity, 1)           L(amihud_illiqudity, 2)  \n                      -4.715e+05                        -7.803e+04  \n         L(amihud_illiqudity, 3)           L(amihud_illiqudity, 4)  \n                      -2.607e+05                         1.958e+05  \n                 turn_over_ratio                    bid_ask_spread  \n                      -1.800e+04                         5.913e+01  \n          beta_monthly_leveraged                                dy  \n                       6.684e+03                        -5.136e+02  \n                        L(dy, 1)                          L(dy, 2)  \n                       2.241e+02                         3.632e+02  \n                        L(dy, 3)                          L(dy, 4)  \n                      -2.862e+02                         1.324e+02  \n      annualised_volatility_open  L(annualised_volatility_open, 1)  \n                      -1.338e+00                        -2.258e+01  \nL(annualised_volatility_open, 2)  L(annualised_volatility_open, 3)  \n                       4.172e+00                         8.258e-01  \nL(annualised_volatility_open, 4)                        market_cap  \n                       1.672e+01                         3.650e-10  \n                L(market_cap, 1)  \n                      -2.723e-10  \n\n\n$best_order\n                       tri          amihud_illiqudity \n                         2                          4 \n           turn_over_ratio             bid_ask_spread \n                         0                          0 \n    beta_monthly_leveraged                         dy \n                         0                          4 \nannualised_volatility_open                 market_cap \n                         4                          1 \n\n$top_orders\n   tri amihud_illiqudity turn_over_ratio bid_ask_spread beta_monthly_leveraged\n1    2                 4               0              0                      0\n2    2                 4               0              0                      0\n3    2                 4               0              0                      0\n4    2                 4               0              0                      0\n5    3                 4               4              0                      0\n6    3                 4               4              0                      0\n7    3                 4               4              0                      0\n8    3                 4               4              0                      0\n9    2                 4               0              0                      1\n10   3                 4               4              0                      1\n11   2                 4               0              1                      1\n12   2                 4               1              1                      1\n13   4                 4               4              4                      4\n14   3                 4               4              1                      1\n15   3                 4               4              1                      1\n16   3                 4               4              1                      1\n17   3                 4               4              1                      2\n18   3                 4               4              2                      2\n19   3                 4               4              2                      2\n20   3                 4               4              2                      2\n   dy annualised_volatility_open market_cap      AIC\n1   4                          4          1 1618.390\n2   4                          4          2 1618.520\n3   4                          3          2 1618.660\n4   3                          3          2 1620.248\n5   4                          3          2 1621.260\n6   4                          3          1 1621.305\n7   4                          2          1 1621.524\n8   4                          2          2 1621.795\n9   3                          3          2 1621.910\n10  4                          3          1 1622.410\n11  3                          3          2 1623.532\n12  3                          3          2 1623.797\n13  4                          4          4 1623.886\n14  4                          3          1 1624.390\n15  4                          3          2 1624.588\n16  4                          2          2 1625.302\n17  4                          3          2 1625.502\n18  4                          3          2 1627.422\n19  4                          3          3 1628.507\n20  3                          3          3 1628.559\n```\n\n\n:::\n:::\n\n\n\n## Select the best model\n\n\n\n::: {.cell}\n\n:::\n\n\n\nSo ardl(2,4,0,0,0,4,4,1) is the best model. So this model has 16 coefficients to estimate from a sample of 129 observations which seems fine.\n\n## ARDL model estimation\n\nProblem with applying OLS is that some variables are non-stationary and some are stationary, which will lead to spurious regression. Therefore, we shall first we estimate the UECM (Unrestricted Error Correction Model) of the underlying ARDL(2,4,0,0,0,4,4,1)\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nTime series regression with \"ts\" data:\nStart = 5, End = 129\n\nCall:\ndynlm::dynlm(formula = full_formula, data = data, start = start, \n    end = end)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-466.20  -66.74   -2.96   66.47  521.82 \n\nCoefficients:\n                                      Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                         -6.243e+03  4.362e+04  -0.143  0.88646    \nL(tri, 1)                           -1.453e-01  5.087e-02  -2.855  0.00521 ** \nL(amihud_illiqudity, 1)             -5.764e+05  3.575e+05  -1.612  0.11003    \nturn_over_ratio                     -1.800e+04  2.510e+05  -0.072  0.94298    \nbid_ask_spread                       5.913e+01  5.423e+02   0.109  0.91339    \nbeta_monthly_leveraged               6.684e+03  4.438e+04   0.151  0.88058    \nL(dy, 1)                            -8.016e+01  6.469e+01  -1.239  0.21814    \nL(annualised_volatility_open, 1)    -2.196e+00  4.612e+00  -0.476  0.63495    \nL(market_cap, 1)                     9.266e-11  3.769e-11   2.459  0.01563 *  \nd(L(tri, 1))                        -1.607e-01  6.463e-02  -2.487  0.01450 *  \nd(amihud_illiqudity)                 3.800e+04  1.739e+05   0.219  0.82746    \nd(L(amihud_illiqudity, 1))           1.428e+05  2.911e+05   0.491  0.62469    \nd(L(amihud_illiqudity, 2))           6.481e+04  2.436e+05   0.266  0.79071    \nd(L(amihud_illiqudity, 3))          -1.958e+05  1.848e+05  -1.060  0.29162    \nd(dy)                               -5.136e+02  8.759e+01  -5.864 5.61e-08 ***\nd(L(dy, 1))                         -2.094e+02  9.267e+01  -2.259  0.02598 *  \nd(L(dy, 2))                          1.538e+02  6.952e+01   2.213  0.02913 *  \nd(L(dy, 3))                         -1.324e+02  7.154e+01  -1.850  0.06714 .  \nd(annualised_volatility_open)       -1.338e+00  1.200e+01  -0.111  0.91145    \nd(L(annualised_volatility_open, 1)) -2.172e+01  1.091e+01  -1.990  0.04929 *  \nd(L(annualised_volatility_open, 2)) -1.755e+01  1.116e+01  -1.572  0.11901    \nd(L(annualised_volatility_open, 3)) -1.672e+01  1.104e+01  -1.514  0.13308    \nd(market_cap)                        3.650e-10  3.516e-11  10.380  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 143.2 on 102 degrees of freedom\nMultiple R-squared:  0.8656,\tAdjusted R-squared:  0.8366 \nF-statistic: 29.86 on 22 and 102 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n## RECM (Restricted Error Correction Model)\n\nUnderlying ARDL(2,4,0,0,0,4,4,1), allowing the constant to join the long-run relationship (case\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nTime series regression with \"zooreg\" data:\nStart = 5, End = 129\n\nCall:\ndynlm::dynlm(formula = full_formula, data = data, start = start, \n    end = end)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-466.20  -66.74   -2.96   66.47  521.82 \n\nCoefficients:\n                                      Estimate Std. Error t value Pr(>|t|)    \nd(L(tri, 1))                        -1.607e-01  6.027e-02  -2.667  0.00881 ** \nd(amihud_illiqudity)                 3.800e+04  1.426e+05   0.267  0.79032    \nd(L(amihud_illiqudity, 1))           1.428e+05  1.961e+05   0.728  0.46804    \nd(L(amihud_illiqudity, 2))           6.481e+04  1.863e+05   0.348  0.72853    \nd(L(amihud_illiqudity, 3))          -1.958e+05  1.534e+05  -1.277  0.20439    \nd(dy)                               -5.136e+02  7.290e+01  -7.046 1.70e-10 ***\nd(L(dy, 1))                         -2.094e+02  7.962e+01  -2.630  0.00977 ** \nd(L(dy, 2))                          1.538e+02  5.883e+01   2.615  0.01017 *  \nd(L(dy, 3))                         -1.324e+02  5.791e+01  -2.286  0.02418 *  \nd(annualised_volatility_open)       -1.338e+00  9.198e+00  -0.145  0.88459    \nd(L(annualised_volatility_open, 1)) -2.172e+01  9.350e+00  -2.323  0.02202 *  \nd(L(annualised_volatility_open, 2)) -1.755e+01  9.877e+00  -1.776  0.07844 .  \nd(L(annualised_volatility_open, 3)) -1.672e+01  9.544e+00  -1.752  0.08256 .  \nd(market_cap)                        3.650e-10  2.877e-11  12.686  < 2e-16 ***\nect                                 -1.453e-01  2.752e-02  -5.279 6.61e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 137.9 on 110 degrees of freedom\n  (0 observations deleted due to missingness)\nMultiple R-squared:   0.87,\tAdjusted R-squared:  0.8523 \nF-statistic: 49.09 on 15 and 110 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n### Long-run levels relationship (cointegration)\n\nLet's test if there is a long-run levels relationship (cointegration) using the bounds test from Pesaran et al. (2001). The bounds F-test (under the case 2) rejects the NULL hypothesis (let's say, assuming alpha = 0.01) with p-value = 0.004418.\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBounds F-test (Wald) for no cointegration\n\ndata:  d(tri) ~ -1 + d(L(tri, 1)) + d(amihud_illiqudity) + d(L(amihud_illiqudity,     1)) + d(L(amihud_illiqudity, 2)) + d(L(amihud_illiqudity,     3)) + d(dy) + d(L(dy, 1)) + d(L(dy, 2)) + d(L(dy, 3)) + d(annualised_volatility_open) +     d(L(annualised_volatility_open, 1)) + d(L(annualised_volatility_open,     2)) + d(L(annualised_volatility_open, 3)) + d(market_cap) +     ect\nF = 7.1129, p-value = 1e-06\nalternative hypothesis: Possible cointegration\nnull values:\n   k    T \n   7 1000 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tBounds t-test for no cointegration\n\ndata:  d(tri) ~ L(tri, 1) + L(amihud_illiqudity, 1) + turn_over_ratio +     bid_ask_spread + beta_monthly_leveraged + L(dy, 1) + L(annualised_volatility_open,     1) + L(market_cap, 1) + d(L(tri, 1)) + d(amihud_illiqudity) +     d(L(amihud_illiqudity, 1)) + d(L(amihud_illiqudity, 2)) +     d(L(amihud_illiqudity, 3)) + d(dy) + d(L(dy, 1)) + d(L(dy,     2)) + d(L(dy, 3)) + d(annualised_volatility_open) + d(L(annualised_volatility_open,     1)) + d(L(annualised_volatility_open, 2)) + d(L(annualised_volatility_open,     3)) + d(market_cap)\nt = -2.8555, Lower-bound I(0) = -3.4248, Upper-bound I(1) = -5.1866,\np-value = 0.5683\nalternative hypothesis: Possible cointegration\nnull values:\n   k    T \n   7 1000 \n```\n\n\n:::\n:::\n\n\n\nSo t=-2.855 lies below lower limit and indicates there is no cointegration and p-value is also 0.5683\n\n## Short-run and long-run multipliers\n\nHere we have the short-run and the long-run multipliers (with standard errors, t-statistics and p-values).\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n                        Term      Estimate   Std. Error     t value\n1                (Intercept) -6.243401e+03 4.361779e+04 -0.14313887\n2          amihud_illiqudity  3.800060e+04 1.739024e+05  0.21851686\n3            turn_over_ratio -1.799948e+04 2.510273e+05 -0.07170328\n4             bid_ask_spread  5.912621e+01 5.422870e+02  0.10903122\n5     beta_monthly_leveraged  6.683610e+03 4.437751e+04  0.15060807\n6                         dy -5.136368e+02 8.758624e+01 -5.86435521\n7 annualised_volatility_open -1.338226e+00 1.200415e+01 -0.11148032\n8                 market_cap  3.649688e-10 3.516023e-11 10.38015991\n      Pr(>|t|)\n1 8.864629e-01\n2 8.274630e-01\n3 9.429785e-01\n4 9.133919e-01\n5 8.805823e-01\n6 5.606853e-08\n7 9.114545e-01\n8 1.173277e-17\n```\n\n\n:::\n:::\n\n\n\n`amihud_illiqudity` has positive and signficant impact on stock returns. Othere coefficients can be interpretted similarly.\n\nWe can also estimate and visualize the delay multipliers along with their standard errors.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](ardl_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n\nThese graphs indicate that most of the variables have almost same impact throughtout time while certain variables affect stock for 4 to 5 months before their impact becomes absorbed. Now let's graphically check the estimated long-run relationship (cointegrating equation) against the dependent variable LRM.\n",
    "supporting": [
      "ardl_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}