---
title: "KSE-30 Interactive Time Series Plot"
author: "Zahid Asghar"
format: html
execute: 
  echo: false
  freeze: auto
editor_options: 
  chunk_output_type: console
---


```{r}
#| warning: false
library(tidyverse) # for data manipulation
library(dygraphs) # for interactive time series plots
```

## Load data

```{r}
#| message: false
#| warning: false
kse30 <- read_csv("docs/data/kse_30_index_v2.csv")

## Format date variable



kse30$date <- as.Date(kse30$date, format = "%d-%b-%y")
 # Deal with date variable
glimpse(kse30)

```

## KSE30 data inspection

```{r}

kse30 %>% glimpse()

kse30 <- kse30 %>% select(date, open, hig,close, low) # Select only required variables

```




```{r}
library(tidyverse)
library(dygraphs)
library(xts)

# Convert to xts
kse30_xts <- kse30 %>%
  select(date, open) %>%
  drop_na() %>%  # Important: Remove any NA values
  arrange(date) %>%  # Make sure dates are sorted
  xts::xts(order.by = .$date)

# Get range
start_date <- min(index(kse30_xts))
end_date <- max(index(kse30_xts))

# Plot
dygraph(kse30_xts, main = "KSE-30 Index (Open Price)") %>%
  dyAxis("y", label = "open") %>%
  dyAxis("x", label = "date") %>%
  dyRangeSelector(dateWindow = c(start_date, end_date))


```

## Difference of kse30 index plot

```{r}
library(dplyr)
library(dygraphs)
library(xts)

# Prepare data first (no xts yet)
kse30_diff <- kse30 %>%
  mutate(p_diff = close - dplyr::lag(close)) %>%
  dplyr::select(date, p_diff) %>%
  drop_na() %>%
  arrange(date)

# Now convert to xts (outside of pipe)
kse30_xts <- xts::xts(kse30_diff$p_diff, order.by = kse30_diff$date)

# Now plot
dygraph(kse30_xts, main = "KSE-30 Daily Close Change") %>%
  dyAxis("y", label = "Change") %>%
  dyAxis("x", label = "Date") %>%
  dyRangeSelector()
```


## KSE30 index plot with moving average

```{r}

kse30 %>% mutate(ma=rollmean(close, 15, fill = NA)) |> 
    select(date, close, ma) %>%
    dygraph(main = "KSE-30 index") %>%
    dyAxis("y", label = "close") %>%
    dyAxis("x", label = "date")  |> 
    dyRangeSelector()


```
