---
title: "[Macroeconomic Forecasting: Structural VAR]{.flow}"
author: "[[Zahid Asghar, Professor, School of Economics, QAU](https://zahedasghar.netlify.app)]{style=color:blue;}"
date: "today"
date-format: "DD-MM-YYYY"
format: 
  revealjs:
    theme: [default, custom.css,styles.scss]
    
    chalkboard: true
    slide-number: c/t
execute: 
  freeze: auto
---

# SVAR models

## Objectives

#### Why a structural VAR 
#### VAR identification: Identifying **A**
#### Impulse responses 
#### Variance decomposition
#### Two identification strategies
  -   Recursive idendtification: Sims (1992)
  -   Non Recursive: Blanchard and Perotti (2002)


## Why a strucutural VAR 

**Effect of monetary policy**. Consider these events:

1. Anticipating a rise in inflation ...
2. The central bank increases the monetary policy interest rate...
inflation still rises, as anticipated. 

  -   One could [**wrongly**]{style="color:red;"} conclude that the interest rate hike led to the inflation. 
  -   It wan an endogenous reaction to expected inflation
  
## Challenge: SVAR Identification 

#### We must identify purely exogenous (policy or other type of) shocks tobe able to trace out its dynamic effects. Identify the structural VAR. 

-   Uncovering the structural model is called identification
-   According to Sims (1986): 

> identification is the interpretation of historically observed variation in 
data in a way that allows the variation to be used to predict the 
consequences of an action not yet undertaken.  

## SVAR Identification

-   Suppose we have the following **Structural VAR(1): 
$AX_t=\beta_0+\beta_1 X_{t-1}+u_t$ Structural shocks u are independent

-   If $X$ variables GDP gap ($y$) and the interest rate ($r$): 
$$X_t=\begin{bmatrix}
y  \\
r  \\ 
\end{bmatrix}$$
the system will be 
$y_t+a_{12}r_t=\beta_{10}+\beta_{12}y_{t-1}+\beta_{12}r_{t-1}+u_{yt}$ 

$a_{21}y_t+r_t=\beta_{20}+\beta_{21}y_{t-1}+\beta_{22}r_{t-1}+u_{rt}$

- - -

In martrix form : $$\begin{bmatrix}
1 & a12\\
a21 & 1 \\
\end{bmatrix}\begin{bmatrix}
y_t\\
r_t\\
\end{bmatrix}=\begin{bmatrix}
\beta_{10}\\
\beta_{20}\\
\end{bmatrix}+\begin{bmatrix}
\beta_{11} & \beta_{12}\\
\beta_{21} & \beta_{22} \\
\end{bmatrix}\begin{bmatrix}
y_{t-1}\\
r_{t-1}\\
\end{bmatrix}+\begin{bmatrix}
u_{yt}\\
u_{rt}\\
\end{bmatrix}$$ 

### $e$ combination of $u$
If we pre multiply this VAR by $A^{-1}$ we get the reduced-form VAR

$A^{-1}A X_t=A^{-1}\beta_0+A^{-1}\beta_1 X_{t-1}+A^{-1}u_t$ 
$X_t=G_0+G_1 X_{t-1}+e_t$  $A^{-1}A=I$ 

- Matrix $A$ also relates the forecast errors of the reduced-form VAR, $e$ and the structural shocks $u$: $e_t=A^{-1}u_t$

## $e$ combinations of $u$

- The forecast errors $e$ are linear combinations of the structural shocks $u$

$e_t=A^{-1}u_t$ 
$e_{yt}=(u_{yt}-a_{12}u_{rt})/(1-a{12}a_{21})$

$e_{rt}=(u_{-a_{12}u_{yt}+rt})/(1-a{12}a_{21})$

## Identification, getting $A$ 

-   The structural VAR cannot be estimated directly. 
-   Start from the reduced-form VAR: 
$X_t=G_0+G_1 X_{t-1}+u_{t}$ 
and get to the structurala one: 
$AX_t=\beta_0+\beta_1 X_{t-1}+u_t$

-   To do that, we need to restrict matrix **A: IDENTIFICATION** 

## Identification, find A
- Get **A** and multiply the reduced-form VAR by **A** to get the structural model, shocks, and contemporaneous relations among variables. 

$AX_t=AG_0+AG_1 X_{t-1}+A e_t$ 

$AX_t=\beta_0+\beta_1 X_{t-1}+y_t$  

$AA^{-1}\beta_0=\beta_0$

## SVAR Identification: getting A 

Usual approach: impose restrictions on matrix **A** which is equivalent to: 

-   Imposing restrictions on the contemporaneous relations among the endogenous variables of the structural model (based on economics).

$$\begin{bmatrix}
1 & 0\\
a21 & 1 \\
\end{bmatrix}\begin{bmatrix}
y_t\\
r_t\\
\end{bmatrix}=\begin{bmatrix}
\beta_{10}\\
\beta_{20}\\
\end{bmatrix}+\begin{bmatrix}
\beta_{11} & \beta_{12}\\
\beta_{21} & \beta_{22} \\
\end{bmatrix}\begin{bmatrix}
y_{t-1}\\
r_{t-1}\\
\end{bmatrix}+\begin{bmatrix}
u_{yt}\\
u_{rt}\\
\end{bmatrix}$$ 

This is what identification is about: [0]{style="color:red;"} in top left corner of A. 

## SVAR Identification: getting A

If we impose $a_{12}=0$, we impose that $y$ is only affected with a lag by a shock to $r$ but that a shock to $y$ affects $r$ contemporaneously  


$y_t=\beta_{10}+\beta_{12}y_{t-1}+\beta_{12}r_{t-1}+u_{yt}$  


$a_{21}y_t+r_t=\beta_{20}+\beta_{21}y_{t-1}+\beta_{22}r_{t-1}+u_{rt}$ 


## SVAR Identification: getting A

-   Be aware that by imposing restrictions on **A** you also impose restrictions on $A^{-}$. Again, if we look at the reduced form,

$A^{-1}A X_t=A^{-1}\beta_0+A^{-1}\beta_1 X_{t-1}+A^{-1}u_t$



$$\begin{bmatrix}
y_t\\
r_t\\
\end{bmatrix}=\begin{bmatrix}
1 & 0\\
a21 & 1 \\
\end{bmatrix}^{-1}\begin{bmatrix}
\beta_{10}\\
\beta_{20}\\
\end{bmatrix}+\begin{bmatrix}
1 & 0\\
a21 & 1 \\
\end{bmatrix}^{-1}\begin{bmatrix}
\beta_{11} & \beta_{12}\\
\beta_{21} & \beta_{22} \\
\end{bmatrix}\begin{bmatrix}
y_{t-1}\\
r_{t-1}\\
\end{bmatrix}+\\ \begin{bmatrix}
1 & 0\\
a21 & 1 \\
\end{bmatrix}^{-1}\begin{bmatrix}
u_{yt}\\
u_{rt}\\
\end{bmatrix}$$ 

-    It is also a restriction on the relation between the forecast errors and the 
structural shocks. Forecast errors of $y$ = structural shocks to y: $e_{yt}=u_{yt}$

## SVAR Identification: restrictions

The matrices product makes the reduced-form VAR: 

$$\begin{bmatrix}
y_t\\
r_t\\
\end{bmatrix}=\begin{bmatrix}
\beta_0\\
-a_{21}\beta_{10}+\beta_{20} \\
\end{bmatrix}+\begin{bmatrix}
\beta_{11} & \beta_{12}\\
-a_{21}\beta_{11}+\beta_{12} & -a_{21}\beta_{12}+\beta_{22} \\
\end{bmatrix}\begin{bmatrix}
y_{t-1}\\
r_{t-1}\\
\end{bmatrix}+\\ \begin{bmatrix}
u_{yt}\\
-a_{21}u_{yt}+u_{rt}\\
\end{bmatrix}$$ 


- The OLS VAR estimation gives:

$$\begin{bmatrix}
y_t\\
r_t\\
\end{bmatrix}=\begin{bmatrix}
g_{10}\\
g_{20} \\
\end{bmatrix}+\begin{bmatrix}
g_{11} & g_{12}\\
g_{21} & g{22} \\
\end{bmatrix}\begin{bmatrix}
y_{t-1}\\
r_{t-1}\\
\end{bmatrix}+ \begin{bmatrix}
e_{yt}\\
e_{rt}\\
\end{bmatrix}$$ 


## SVAR Identification : restrictions
-   With the restriction, the number of unknown parameters in the structural model is equal to the number of equations known from the estimated VAR 
-   Substitute the results from the estimation for these 9 parameters $g_{10},g_{11},g_{12},g_{20},g_{21},g_{22},\sigma_{ey}^2,\sigma_{er}^2 and \sigma_{ey-er}$  
into 9 equations, to solve for : 

$a_{21}, \beta_{10},\beta_{20},\beta_{11},\beta_{21},\beta_{22}, \sigma_{vy}^2 and \sigma_{vr}^2$ 
- The structural shocks may also be recovered. 


## SVAR Identification: restrictions
 Summary of SVAR Identification up to now: 
-   Get the structural model, 
-   to do that, we need to get A, so
-   impose restrictions on A, based on economics, to recover the structural shocks 
and the structural parameters, using the reduced-form estimation. 

#### Therefore, SVAR identification is about imposing restrictions on matrix A.

## SVAR Identification: how many restrictions?
-   The minimum number of restrictions required: **difference** between the number of unknown and known elements. Let **n** be the number of variable in the VAR. 

-   **Unknown**: as the elements of the diagonal of **A** are equal 1's, there are $n(n-1)$ unknown elements in **A**. There are also n unknown variances of $u$. The total is: $n(n-1)+n=n^2$. 

- **Known elements**: the estimation allows us to get $n(n-1)/2+n=n(n+1)/2$ distinct elements contained in the **symmetric** var-cov matrix of the errors: $Ee_t e_t'=\Sigma_e$.

## SVAR Identification: how many restrictions?

**Why the known** elements are $n(n+1)/2$? The distinct elements contained in the symmetric var-cov matrix of the forecast errors: $Ee_t e_t'=\Sigma_e$ 

- Because there are n distinct elements in the diagonal of $\Sigma_e$ and $n(n-1)/2$ distinct elements in the upper triangular part of $\Sigma_e$. The total number of known elements is:
$n+n(n-1)/2=n(n+1)/2$.

- Thus, impose $n^2-n(n+1)/2=n(n-1)/2$ restrictions on **A**.A VAR with 3 variables requires 3(3-1)/2=3 restrictions on **A**; A VAR with 4 variables requires 4(4-1)/2=6 restrictions on **A**.


## Impulse Responses

- Impulse responses trace the effects of structural shocks on the endogenous variables over time.

- Each response includes the effect of a specific shock on one of the endogenous variables of the system at impact t, then on **t+1**, and so on. 

- Transform our structural autoregressive vector $AX_t=\beta_0+\beta_1 X_{t-1}+u_t$ into a moving average representation:
$X_t=\mu+\sum_{i=0}^{\infty}C_i u_t$


## Variance Decomposition 

- Forecast errors and the relationships among the variables. 

- Propotion of the movements of a variable due to shocks to itself and shocks to other variables in the system.

-  This forecast error variance decomposition and the foreces behind business cycles.

## Variance Decomposition

-   Are all business cycles alike? Are GDP surprises mostly due to technology shocks or to monetary policy shocks?

-   Are demand shocks the main source of GDP forecast errors at long hirzons?

-   In our recursive ordering for $y$ and $r$, all of the one period forecast-error variance of $y$ is due to shocks to $u_{yt}$. At longer horizons the explanatory share of shocks to $u_{yt}$ will diminish. 


# Two identification strategies

## SVAR Identification: recursive ordering 

-   In our example the residuals take on a recursive ordering:
Matrix $A^{-1}$ is lower triangular ( only has zeros above the diagonal).

$e_{yt}=u_{yt}$ and $e_{rt}=u_{rt}-a_{21}u_{yt}$

$$\begin{bmatrix}
e_{yt}\\
e_{rt}\\
\end{bmatrix}=\begin{bmatrix}
1 & 0\\
-a_{21} & 1 \\
\end{bmatrix}\begin{bmatrix}
u_{yt}\\
u_{rt}\\
\end{bmatrix}$$

-   The recursive ordering means that there is a sequential chain.

## SVAR Identification: recursive ordering

-   Shocks to $r$ only affects output gap $y$ with a lag:
$y_t=\beta_0+\beta_1 y_{t-1}+\beta_2 r_{t-1}+u_{yt}$ 
-   Both shocks have contemporaneous effects on the interest rate$r$:
$r_t+a_{21}y_t=\beta_0+\beta_1 y_{t-1}+\beta_2 r_{t-1}+u_{rt}$

-   If $r$ is the policy rate, then the recursive ordering is consistent with the view that monetary policy responds to output gap $y$ with a lag, but responds to the interest rate $r$ contemporaneously.

## SVAR Identification: recursive ordering

-    Another example: a three-variable recursive ordering with $y$, $\pi$(inflation) and $r$:

$e_{yt}=u_{yt}$
$e_{\pi t}=-a_{21}u_{yt}+u_{\pi t}$
$e_{rt}=(-a_{31}+a_{21}a_{32})u_{yt}-a_{32}u_{\pi t}+u_{rt}$

$$\begin{bmatrix}
e_{yt}\\
e_{\pi t}\\
e_{rt}\\
\end{bmatrix}=\begin{bmatrix}
1 & 0 & 0\\
-a_{21} & 1 & 0\\
-a_{31}+a_{21}a_{32} & -a_{32} & 1\\
\end{bmatrix}\begin{bmatrix}
u_{yt}\\
u_{\pi t}\\
u_{rt}\\
\end{bmatrix}$$
- If movements of $r$ are monetary policy(MP) decisions, policy is reacting to output $y$ and inflation $\pi$ within the period. All shocks have contemporaneous effects on $r$.
- The policy rate $r$ affects output $y$ with a lag, and inflation $\pi$ with a lag.

## SVAR Identification: recursive ordering

-  The good news is that it is easy to find matrix $A^{-1}$ and $A$ when one has a recursive ordering. And with $A$ we get the impulse-responses. 
-   Any invertible matrix may be broken into two lower triangular factors(Choleski factors). It is a numerica technique(not economics) to easily estimate a recursive ordering.
-   You must be aware of the economic restrictions you are imposing. [The zeros]{style="color:red"} on the upper side [are RESTRICTIONS]{style="color:red"} on the contemporaneous effects of the shocks.

## SVAR Identification: recursive ordering

- Indeed, when one has a recursive odering. 

- $A^{-1}$ is the **Choleski factor** of the variance-covariance matrix. 

-   Why? substitute $e_t=A^{-1}u_t$ into $Ee_t e_t'=\Sigma_e$ and get $A^{-1}\Sigma_u A^{-1'}=\Sigma_e$. 

-   Assuming that $u_tu_t'$ is diagonal, then $A^{-1}IA^{-1}'=\Sigma_e$ same as $\Sigma_e=A^{-1}A^{-1'}$. The inverse of $A$ is lower triangular consistent with a recursive ordering.

Not that assuming $\Sigma_u=1$ implies that $A$ will not have $1s$ on the diagonal.

## SVAR Identification: recursive ordering
- If correlations between the errors are low, the order is irrelevant. But 
usually, correlations are strong and the order matters. 
- Deciding the ordering (restrictions) to be imposed is crucial. Use 
economic intuition to decide it.
- It is impractical to try all possible orderings. With 4 variables there are 
4!=24 possible orderings. Too many.

## SVAR Identification: recursive ordering 

-   If you are sure that there is a recursive ordering, or sequential chain, you 
must then know in what order the variables are recursive. 
-    It is often difficult to justify the economics of a recursive ordering

## Example : Sims(1992)

> *Interepreting the macroeconomic time series facts* European Economic Review

-   Sims estimated a VAR to trace the effect of a shock to monetary policy (Central Bank Interest Rate) using specific ordering. 

-   To assess the empirical support for alternative views (models) about monetary policy: VAR agenda.

-   He included:
    -   Federal Funds Rate(ff) and the logs of $M1$ (lm), CPI (lp), and **Industrial production**(ly).
    The VAR was estimated using 14 lags during the sample period : 1958:04- 1991:02 
    
## Example : Sims(1992)

-   The policy variable (ff) was observed first. So the ordering is equivalent to assuming that:

1.  Shocks to the nominal interest rate **ff**, represent monetary policy shocks.
2.  A shcok to the policy variable affects all other variables contemporaneously.
3.  The variable that is affected by all the others, within the period, is ordered last. 

4.  Authorities only observe non-policy variables with a lag.

## Example : Sims(1992)

Empirical results:


## SVAR Identification: non recursive ordering

-   Until now we have used $e_t=A^{-1}u_t$ to show the relation between forecast errors and structural shocks.
-   Bernanke and Mihov (1998), Blanchard and Perotti (2002), and other authors use a more general way of relating errors and shocks in structural VARs: $Ae_t=Bu_t$.
-   The specification of these equations can have both errors and shocks on 
the right hand side. 
To get the system responses to shocks one needs to have $e_t=A^{-1}Bu_t$. or
$e_t=Fu_t$. So we use the estimated $A$ and $B$ to compute $F=A^{-1}B$.

## SVAR Identification: non recursive ordering

> “An empirical characterization of the dynamic effects of changes in government 
spending and taxes on output.” Quarterly Journal of Economics, 117(4):1329–1368, 2002.

Use a semi-recursive VAR to econometrically identify fiscal policy 
shocks; i.e. exogenous movements in public expenditure/taxes. 
- They estimate a VAR: 
  -   Using contemporaneous identification restrictions on variables. 
  -   Imposing, on matrix A, coefficients estimated outside the VAR.
-   They pay careful attention to institutional procedures and periods of 
tax collection and public spending. 

## Exmaple: Blanchard and Perotti (2002)

-   The **VAR** is $X_t=G(L)X_{t-1}+e_t$ where $X_t=[S_t,T_t,Y_t]$ includes the logs of quarterly real per capita government spending, taxes, and GDP, respectively. 

-   And $e_t=[e_t^S,e_t^T,e_t^Y$ is the vector of reduced form residuals or forecast errors of spending, taxes, and GDP, respectively.

-   **Spending**: government **consumption** and **investment**.
-   **Revenue**: total **taxes** minus **transfers** and minus interest payments. 

## Exmaple: Blanchard and Perotti (2002)

> An empirical characterization of the dynamic effects ...

-   The whole system is:
$e_t^{S}=b_1e_t^{y}+b_2e_t^{T}+b_3e_t^{S}$
$e_t^{T}=a_1e_t^{y}+a_2e_t^{S}+b_6e_t^{T}$
$e_t^{y}=c_1e_t^{T}+c_2e_t^{S}+c_3e_t^{y}$

$$\begin{bmatrix}
1 & 0 & -b_1\\
0 & 1 & -a_1\\
-c_1 & -c_2 & 1\\
\end{bmatrix}\begin{bmatrix}
e_t^{S}\\
e_t^{T}\\
e_t^{y}\\
\end{bmatrix}=\begin{bmatrix}
1 & b_2 & 0\\
a_2 & 1 & 0\\
0 & 0 & 1\\
\end{bmatrix}\begin{bmatrix}
u_t^{S}\\
u_t^{T}\\
u_t^{y}\\
\end{bmatrix}$$
These are matrices $A$ and $B$ to be estimated.

-   $U_t=[u_t^S,u_t^T,u_t^Y]$ is the vector of structural shocks to spending, taxes, and GDP. 

## Exmaple: Blanchard and Perotti (2002)
> An empirical characterization of the dynamic effects ... 

- Forecast errors are a mix of $e$ and structural shocks $u$:

1. $e_t^S=b_1 e_t^{y}+b_2 e_t^{T}+u_t^S$ 
 Unexpected movements in spending ($e_t^S$) are due to shocks to GDP forecast errors ($b_1 e_t^{y}$) structural shocks to taxes ($b_2 e_t^{T}$) and structural shocks to government spending ($u_t^S$). 
-   Key: At high frequencies (quarterly), there is no discretionary, within the period, 
response of government spending to unexpected movements in $y: b1$ is always 0.
-   Are taxes responding to spending decisions? Or the reverse? Here government spending decisions go before tax decisions so $b2 = 0$.

## Exmaple: Blanchard and Perotti (2002)
> An empirical characterization of the dynamic effects ...

2. $e_t^T=a_1 e_t^{y}+a_2 e_t^{S}+u_t^T$ 
 
-   Forecast errors in taxes are due to surprises in GDP ($a_1 e_t^{y}$), surprises in spending ($a_2 u_t^{S}$), and structural shocks to taxes ($u_t^T$).
-   They constructed the elasticity to output of taxes minus transfers ( ) to get the 
automatic effect of GDP on taxes within the quarter. On average
-   Assumed that spending decisions go first, so a2 was estimated with the SVAR 

##     Exmaple: Blanchard and Perotti (2002)

[SPENDING SHOCKS]{style="color:blue"} VAR 4 lags 1960:1 1997:4 ($a_2neq0$,$b_2=0$)

## R Codes for Blanchard and Perotti (2002)

 